name: Node Latest
description: Install the latest Node.js version
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: '22' # Update this line to the latest Node.js version
