name: Node.js Latest
description: Install the latest version of Node.js
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        cache: yarn
        node-version: 'latest'
