// AUTO-GENERATED by dd-compile from bee-queue.analysis.json
// To customize plugin behavior, edit this file directly.
// Re-running dd-compile will show a diff but won't overwrite without confirmation.

'use strict'

const ConsumerPlugin = require('../../dd-trace/src/plugins/consumer')
const Extractors = require('./extractors')

class BeeQueueConsumerPlugin extends ConsumerPlugin {
  static get id () {
    return 'bee-queue'
  }

  constructor (...args) {
    super(...args)
    this.subscribe()
  }

  subscribe () {
    this.addBind('tracing:apm:bee-queue:queue:process:asyncStart', (ctx) => this.queueProcessStart(ctx))
    this.addBind('tracing:apm:bee-queue:queue:process:error', (ctx) => this.error(ctx))
    this.addBind('tracing:apm:bee-queue:queue:process:asyncEnd', (ctx) => this.finish(ctx))
    this.addSub('tracing:apm:bee-queue:queue:process:asyncEnd', (ctx) => this.finish(ctx))
  }

  queueProcessStart (ctx) {
    const tags = Extractors.queueProcessConsumer(ctx)
    const options = {
      resource: tags['resource.name'] || 'process',
      meta: tags
    }
    return this.startSpan(options, ctx)
  }

  error (ctx) {
    const span = ctx?.currentStore?.span
    if (span) {
      this.addError(span, ctx.error)
    }
    return ctx.parentStore
  }

  finish (ctx) {
    const span = ctx?.currentStore?.span
    if (span) {
      super.finish(ctx)
    }
    return ctx.parentStore
  }
}

module.exports = BeeQueueConsumerPlugin
