// AUTO-GENERATED by dd-compile from bee-queue.analysis.json
// To customize tag extraction, edit this file directly.
// Re-running dd-compile will show a diff but won't overwrite without confirmation.

'use strict'

const BeeQueueExtractors = {
  queueProcessConsumer (ctx) {
    return {
      'messaging.system': 'bee-queue',
      'messaging.destination.name': ctx.self?.name || ctx.this?.name || 'unknown',
      'messaging.operation': 'process'
    }
  },

  queueCloseProducer (ctx) {
    return {
      'messaging.system': 'bee-queue',
      'messaging.destination.name': ctx.self?.name || ctx.this?.name || 'unknown',
      'messaging.operation': 'close'
    }
  },

  queueConnectProducer (ctx) {
    return {
      'messaging.system': 'bee-queue',
      'messaging.destination.name': ctx.self?.name || ctx.this?.name || 'unknown',
      'messaging.operation': 'connect'
    }
  }
}

module.exports = BeeQueueExtractors
