// AUTO-GENERATED by dd-compile from bee-queue.analysis.json
// To customize tag extraction, edit this file directly.
// Re-running dd-compile will show a diff but won't overwrite without confirmation.

'use strict'

function jobSaveProducer (ctx) {
  return {
    'component': 'bee-queue',
    'span.kind': 'producer',
    'messaging.system': 'bee-queue',
    'messaging.destination.name': ctx.self?.queue?.name || ctx.this?.queue?.name,
    'messaging.operation': 'produce'
  }
}

function queueProcessConsumer (ctx) {
  return {
    'component': 'bee-queue',
    'span.kind': 'consumer',
    'messaging.system': 'bee-queue',
    'messaging.destination.name': ctx.self?.name || ctx.this?.name,
    'messaging.operation': 'process',
    'span.kind': 'consumer'
  }
}

function queueSaveallProducer (ctx) {
  return {
    'component': 'bee-queue',
    'span.kind': 'producer',
    'messaging.system': 'bee-queue',
    'messaging.operation': 'produce_bulk'
  }
}

module.exports = {
  'jobSaveProducer': jobSaveProducer,
  'queueProcessConsumer': queueProcessConsumer,
  'queueSaveallProducer': queueSaveallProducer
}
