// AUTO-GENERATED by dd-compile
'use strict'

const CompositePlugin = require('../../dd-trace/src/plugins/composite')
const BeeQueueProducerPlugin = require('./producer')
const BeeQueueConsumerPlugin = require('./consumer')

class BeeQueuePlugin extends CompositePlugin {
  static get id () {
    return 'bee-queue'
  }

  static get plugins () {
    return {
      producer: BeeQueueProducerPlugin,
      consumer: BeeQueueConsumerPlugin
    }
  }
}

module.exports = BeeQueuePlugin
