// AUTO-GENERATED by dd-compile
'use strict'

const CompositePlugin = require('../../dd-trace/src/plugins/composite')
const BeeQueueConsumerPlugin = require('./consumer')
const BeeQueueProducerPlugin = require('./producer')

class BeeQueuePlugin extends CompositePlugin {
  static get id () {
    return 'bee-queue'
  }

  static get plugins () {
    return {
      consumer: BeeQueueConsumerPlugin,
      producer: BeeQueueProducerPlugin
    }
  }
}

module.exports = BeeQueuePlugin
