// AUTO-GENERATED by dd-compile from bee-queue.analysis.json
// To customize plugin behavior, edit this file directly.
// Re-running dd-compile will show a diff but won't overwrite without confirmation.

'use strict'

const ProducerPlugin = require('../../dd-trace/src/plugins/producer')
const Extractors = require('./extractors')

class BeeQueueProducerPlugin extends ProducerPlugin {
  static get id () {
    return 'bee-queue'
  }

  constructor (...args) {
    super(...args)
    this.subscribe()
  }

  subscribe () {
    // Subscribe to diagnostic channels for each instrumented operation
    // For tracePromise: :start, :error, :asyncEnd channels
    // Note: :error may not always fire; fallback error handling in finish()
    this.addBind('tracing:apm:bee-queue:job:save:start', (ctx) => this.jobSaveStart(ctx))
    this.addSub('tracing:apm:bee-queue:job:save:error', (ctx) => this.error(ctx))
    this.addSub('tracing:apm:bee-queue:job:save:end', (ctx) => this.finish(ctx))
    this.addSub('tracing:apm:bee-queue:job:save:asyncEnd', (ctx) => this.finish(ctx))
    this.addBind('tracing:apm:bee-queue:queue:saveall:start', (ctx) => this.queueSaveallStart(ctx))
    this.addSub('tracing:apm:bee-queue:queue:saveall:error', (ctx) => this.error(ctx))
    this.addSub('tracing:apm:bee-queue:queue:saveall:end', (ctx) => this.finish(ctx))
    this.addSub('tracing:apm:bee-queue:queue:saveall:asyncEnd', (ctx) => this.finish(ctx))
  }

  jobSaveStart (ctx) {
    const tags = Extractors.jobSaveProducer(ctx)
    const options = {
      meta: tags,
      resource: tags['resource.name'] || 'save'
    }
    return this.startSpan(options, ctx)
  }

  queueSaveallStart (ctx) {
    const tags = Extractors.queueSaveallProducer(ctx)
    const options = {
      meta: tags,
      resource: tags['resource.name'] || 'saveAll'
    }
    return this.startSpan(options, ctx)
  }

  error (ctx) {
    const span = ctx?.currentStore?.span
    if (span && ctx.error) {
      this.addError(ctx.error, span)
    }
    return ctx.parentStore
  }

  finish (ctx) {
    const span = ctx?.currentStore?.span
    if (span) {
      // If there's an error in the context, add it to the span
      // This handles cases where :error channel wasn't published but ctx.error exists
      // (e.g., with tracePromise when promise rejects)
      if (ctx.error) {
        this.addError(ctx.error, span)
      }
      super.finish(ctx)
    }
    return ctx.parentStore
  }
}

module.exports = BeeQueueProducerPlugin
