// AUTO-GENERATED by dd-compile from bullmq.analysis.json
// To customize plugin behavior, edit this file directly.
// Re-running dd-compile will show a diff but won't overwrite without confirmation.

'use strict'

const ConsumerPlugin = require('../../dd-trace/src/plugins/consumer')
const Extractors = require('./extractors')

class BullmqConsumerPlugin extends ConsumerPlugin {
  static get id () {
    return 'bullmq'
  }

  constructor (...args) {
    super(...args)
    this.subscribe()
  }

  subscribe () {
    this.addBind('tracing:apm:bullmq:worker:on:start', (ctx) => this.workerOnStart(ctx))
    this.addBind('tracing:apm:bullmq:worker:on:error', (ctx) => this.error(ctx))
  }

  workerOnStart (ctx) {
    const tags = Extractors.workerOnConsumer(ctx)
    const name = 'bullmq.on'
    const options = {
      meta: tags,
      resource: tags['resource.name'] || 'on'
    }
    return this.startSpan(name, options, ctx)
  }

  error (ctx) {
    const span = ctx?.currentStore?.span
    if (span) {
      span.setTag('error', ctx.error)
    }
    return ctx.parentStore
  }

  finish (ctx) {
    const span = ctx?.currentStore?.span
    if (span) {
      super.finish(ctx)
    }
    return ctx.parentStore
  }
}

module.exports = BullmqConsumerPlugin
