// AUTO-GENERATED by dd-compile from bullmq.analysis.json
// To customize tag extraction, edit this file directly.
// Re-running dd-compile will show a diff but won't overwrite without confirmation.

'use strict'

const BullmqExtractors = {
  queueAddProducer (ctx) {
    return {
      'messaging.system': 'bullmq',
      'messaging.destination.name': ctx.self?.name || ctx.this?.name,
      'messaging.operation': 'produce'
    }
  },

  workerOnConsumer (ctx) {
    return {
      'messaging.system': 'bullmq',
      'messaging.destination.name': ctx.self?.name || ctx.this?.name,
      'messaging.operation': 'consume',
      'messaging.message.id': ctx.self?.keys.id || ctx.this?.keys.id
    }
  }
}

module.exports = BullmqExtractors
