// AUTO-GENERATED by dd-compile
'use strict'

const CompositePlugin = require('../../dd-trace/src/plugins/composite')
const BullmqProducerPlugin = require('./producer')
const BullmqConsumerPlugin = require('./consumer')

class BullmqPlugin extends CompositePlugin {
  static get id () {
    return 'bullmq'
  }

  static get plugins () {
    return {
      producer: BullmqProducerPlugin,
      consumer: BullmqConsumerPlugin
    }
  }
}

module.exports = BullmqPlugin
