jobs:
  - job: win32
    pool:
      vmImage: vs2017-win2016
    strategy:
      matrix:
        x32:
          arch: x32
        x64:
          arch: x64
    steps:
    - bash: yarn versions
      displayName: Versions

    - bash: yarn install
      displayName: Install dependencies

    - bash: yarn prebuild
      displayName: Compile prebuilt binaries
      env:
        ARCH: $(arch)
