name: Node Setup
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with:
        cache: yarn
        node-version: '14'
      run: |
          sudo hostnamectl set-hostname testrunner
