// AUTO-GENERATED by dd-compile from nats-io-nats-core.analysis.json
// To customize plugin behavior, edit this file directly.
// Re-running dd-compile will show a diff but won't overwrite without confirmation.

'use strict'

const ClientPlugin = require('../../dd-trace/src/plugins/client')
const Extractors = require('./extractors')

class NatsIoNatsCoreClientPlugin extends ClientPlugin {
  static get id () {
    return '@nats-io/nats-core'
  }

  static get prefix () {
    return 'apm:@nats-io/nats-core:natsconnectionimpl:prototype:request'
  }

  static get operation () {
    return 'request'
  }

  static peerServicePrecursors = ['messaging.destination.name']

  asyncStart (ctx) {
    const subject = ctx.subject || 'unknown'

    this.startSpan({
      resource: 'request',
      type: 'messaging',
      meta: {
        'component': '@nats-io/nats-core',
        'span.kind': 'client',
        'messaging.system': '@nats-io/nats-core',
        'messaging.destination.name': subject
      }
    }, ctx)
  }
  
  // asyncEnd and end delegate to finish() which has the required guard
  asyncEnd (ctx) {
    this.finish(ctx)
  }

  end (ctx) {
    this.finish(ctx)
  }

  // You may modify this method, but the guard below is REQUIRED and MUST NOT be removed!
  finish (ctx) {
    // CRITICAL GUARD - DO NOT REMOVE: Ensures span only finishes when operation completes
    if (!ctx.hasOwnProperty('result') && !ctx.hasOwnProperty('error')) return

    const span = ctx?.currentStore?.span
    if (span) {
      super.finish(ctx)
    }
  }
}

module.exports = NatsIoNatsCoreClientPlugin
