// AUTO-GENERATED by dd-compile from nats-io-nats-core.analysis.json
// To customize tag extraction, edit this file directly.
// Re-running dd-compile will show a diff but won't overwrite without confirmation.

'use strict'

function natsconnectionimplPublishProducer (ctx) {
  return {
    operation: 'nats.publish',
    resource: 'publish',
    meta: {
      'component': '@nats-io/nats-core',
      'span.kind': 'producer'
    }
  }
}

function protocolhandlerProcessmsgConsumer (ctx) {
  return {
    operation: 'nats.process',
    resource: 'processMsg',
    meta: {
      'component': '@nats-io/nats-core',
      'span.kind': 'consumer'
    }
  }
}

function natsconnectionimplRequestClient (ctx) {
  return {
    operation: 'nats.request',
    resource: 'request',
    meta: {
      'component': '@nats-io/nats-core',
      'span.kind': 'client'
    }
  }
}

module.exports = {
  'tracing:apm:@nats-io/nats-core:natsconnectionimpl:prototype:publish': natsconnectionimplPublishProducer,
  'tracing:apm:@nats-io/nats-core:protocolhandler:prototype:processmsg': protocolhandlerProcessmsgConsumer,
  'tracing:apm:@nats-io/nats-core:natsconnectionimpl:prototype:request': natsconnectionimplRequestClient
}
