// AUTO-GENERATED by dd-compile
'use strict'

const CompositePlugin = require('../../dd-trace/src/plugins/composite')
const NatsIoNatsCoreProducerPlugin = require('./producer')
const NatsIoNatsCoreConsumerPlugin = require('./consumer')
const NatsIoNatsCoreClientPlugin = require('./client')

class NatsIoNatsCorePlugin extends CompositePlugin {
  static get id () {
    return '@nats-io/nats-core'
  }

  static get plugins () {
    return {
      producer: NatsIoNatsCoreProducerPlugin,
      consumer: NatsIoNatsCoreConsumerPlugin,
      client: NatsIoNatsCoreClientPlugin
    }
  }
}

module.exports = NatsIoNatsCorePlugin
