// AUTO-GENERATED by dd-compile from nats-io-nats-core.analysis.json
// To customize plugin behavior, edit this file directly.
// Re-running dd-compile will show a diff but won't overwrite without confirmation.

'use strict'

const ProducerPlugin = require('../../dd-trace/src/plugins/producer')
const Extractors = require('./extractors')
const { DsmPathwayCodec, getMessageSize } = require('../../dd-trace/src/datastreams')

class NatsIoNatsCoreProducerPlugin extends ProducerPlugin {
  static get id () {
    return '@nats-io/nats-core'
  }

  static get prefix () {
    return 'apm:@nats-io/nats-core:natsconnectionimpl:prototype:publish'
  }

  static get operation () {
    return 'publish'
  }

  static peerServicePrecursors = ['messaging.destination.name']

  bindStart (ctx) {
    const subject = ctx.subject || 'unknown'

    const span = this.startSpan({
      resource: 'publish',
      type: 'messaging',
      meta: {
        component: '@nats-io/nats-core',
        'span.kind': 'producer',
        'messaging.system': '@nats-io/nats-core',
        'messaging.destination.name': subject
      }
    }, ctx)

    // Context Propagation: Inject trace context into NATS headers
    if (span && ctx.options && ctx.options.headers) {
      const headerAdapter = this._createHeaderAdapter(ctx.options.headers)
      this.tracer.inject(span, 'text_map', headerAdapter)
    }

    // DSM: Set checkpoint and encode pathway context into NATS headers
    if (this.config.dsmEnabled && span && ctx.options && ctx.options.headers) {
      const payloadSize = getMessageSize({ value: ctx.data })
      const edgeTags = ['direction:out', `topic:${subject}`, 'type:nats']

      const dataStreamsContext = this.tracer.setCheckpoint(edgeTags, span, payloadSize)

      // Encode DSM context into NATS headers using an adapter
      const headerAdapter = this._createHeaderAdapter(ctx.options.headers)
      DsmPathwayCodec.encode(dataStreamsContext, headerAdapter)
    }

    return ctx.currentStore
  }

  // Creates an adapter that allows DsmPathwayCodec to work with NATS MsgHdrs
  _createHeaderAdapter (natsHeaders) {
    return new Proxy({}, {
      set (target, prop, value) {
        // DsmPathwayCodec sets headers like: carrier['dd-pathway-ctx-base64'] = 'value'
        // We need to call natsHeaders.set(key, value)
        if (natsHeaders && typeof natsHeaders.set === 'function') {
          natsHeaders.set(String(prop), String(value))
        }
        target[prop] = value
        return true
      },
      get (target, prop) {
        if (natsHeaders && typeof natsHeaders.get === 'function') {
          return natsHeaders.get(String(prop))
        }
        return target[prop]
      }
    })
  }

  // asyncEnd and end delegate to finish() which has the required guard
  asyncEnd (ctx) {
    this.finish(ctx)
  }

  end (ctx) {
    this.finish(ctx)
  }

  error (ctx) {
    // Call parent's error to set error tag
    super.error(ctx)
    // Then finish the span
    this.finish(ctx)
  }

  // You may modify this method, but the guard below is REQUIRED and MUST NOT be removed!
  finish (ctx) {
    // CRITICAL GUARD - DO NOT REMOVE: Ensures span only finishes when operation completes
    if (!ctx.hasOwnProperty('result') && !ctx.hasOwnProperty('error')) return

    const span = ctx?.currentStore?.span
    if (span) {
      super.finish(ctx)
    }
  }
}

module.exports = NatsIoNatsCoreProducerPlugin
