//! Chunk assembly: the core of `span_processor.js`'s `process()`.
//!
//! Started spans buffer per segment until the segment's finished count matches its
//! started count, or crosses the `flushMinSpans` threshold, and then the completed
//! chunk is emitted. Deliberately *not* replicated, per the PoC's non-goals: git
//! metadata tagging, span stats, OTel semantics rewriting and sampling. Every
//! completed chunk is exported unconditionally.
//!
//! State here is persistent across flush batches, because a segment can still be
//! open when a flush fires. Everything it holds is an owned string resolved during
//! its own batch's decode — no id outlives the interning window it came from.

use std::collections::HashMap;
use std::hash::{BuildHasherDefault, Hasher};
use std::rc::Rc;

use crate::decode::Event;
use crate::encode;
use crate::wire::{
    FRAMEWORK_EXPRESS, MIDDLEWARE_EXPRESS, KEY_ERROR, KEY_ERROR_MESSAGE, KEY_ERROR_STACK, KEY_ERROR_TYPE,
    KEY_HTTP_STATUS_CODE, KEY_OPERATION_NAME, KEY_RESOURCE_NAME, KEY_SERVICE_NAME, KEY_SPAN_KIND,
    KEY_SPAN_TYPE,
};

const META_LANGUAGE: &str = "language";
const META_SPAN_LINKS: &str = "_dd.span_links";
const META_EVENTS: &str = "events";
const META_BASE_SERVICE: &str = "_dd.base_service";
const METRIC_PROCESS_ID: &str = "process_id";
const METRIC_TOP_LEVEL: &str = "_dd.top_level";
const METRIC_MEASURED: &str = "_dd.measured";
const META_VERSION: &str = "version";

// Everything a web-server span carries that follows from being a web-server span. None
// of this travels on the wire: the specialized events send the method, the URL, the
// status, the route and one framework word, and the rest is filled in here.
const META_COMPONENT: &str = "component";
const META_SPAN_KIND: &str = "span.kind";
const META_HTTP_METHOD: &str = "http.method";
const META_HTTP_URL: &str = "http.url";
const META_HTTP_STATUS_CODE: &str = "http.status_code";
const META_HTTP_ROUTE: &str = "http.route";
const META_INTEGRATION: &str = "_dd.integration";
const META_TRACE_ID_HIGH: &str = "_dd.p.tid";
const VALUE_SERVER: &str = "server";
const VALUE_WEB: &str = "web";
const NAME_WEB_REQUEST: &str = "web.request";
const NAME_ROUTER_MIDDLEWARE: &str = "router.middleware";
const NAME_EXPRESS_MIDDLEWARE: &str = "express.middleware";
const COMPONENT_ROUTER: &str = "router";
const NAME_EXPRESS_REQUEST: &str = "express.request";
const COMPONENT_HTTP: &str = "http";
const COMPONENT_EXPRESS: &str = "express";

// `normalizeSpan` in `encode/tags-processors.js`, which both JS encoders run before
// writing a span. Applied here so a formatted span is already normalised whichever
// protocol encodes it.
const DEFAULT_SPAN_NAME: &str = "unnamed_operation";
const DEFAULT_SERVICE_NAME: &str = "unnamed-service";
const MAX_NAME_LENGTH: usize = 100;
const MAX_SERVICE_LENGTH: usize = 100;
const MAX_TYPE_LENGTH: usize = 100;

/// Retired builders kept for reuse. The pool only has to cover spans alive at once, not
/// a whole batch: uncapped, a 150k-span batch retained 150k builders — some 30 MB, grown
/// by repeated doubling — to serve a working set of a handful.
const POOL_CAPACITY: usize = 1024;

/// Hasher for the two id-keyed maps. Span and segment ids are already pseudo-random
/// 63-bit values, so the default `SipHash-1-3` buys nothing here — its HashDoS
/// resistance protects against attacker-chosen keys, and these keys are generated by
/// the tracer itself. One multiply-xorshift avalanches the bits `hashbrown` needs from
/// both ends of the word.
#[derive(Default)]
struct IdHasher(u64);

impl Hasher for IdHasher {
    fn finish(&self) -> u64 {
        self.0
    }

    fn write(&mut self, bytes: &[u8]) {
        // Never reached: the only keys are `u64`.
        for byte in bytes {
            self.0 = (self.0 ^ *byte as u64).wrapping_mul(0x0100_0000_01b3);
        }
    }

    fn write_u64(&mut self, value: u64) {
        let mixed = value.wrapping_mul(0x9E37_79B9_7F4A_7C15);
        self.0 = mixed ^ (mixed >> 32);
    }
}

type IdMap<V> = HashMap<u64, V, BuildHasherDefault<IdHasher>>;

/// The constant `meta` / `metrics` keys every span carries, allocated once. Building
/// them with `Rc::from(CONST)` inside `finalize` instead cost four to six heap
/// allocations plus a memcpy per span, purely to spell out a `&'static str`.
struct ConstantKeys {
    language: Rc<str>,
    component: Rc<str>,
    span_kind: Rc<str>,
    http_method: Rc<str>,
    http_url: Rc<str>,
    http_status_code: Rc<str>,
    http_route: Rc<str>,
    integration: Rc<str>,
    trace_id_high: Rc<str>,
    error_message: Rc<str>,
    error_type: Rc<str>,
    error_stack: Rc<str>,
    value_server: Rc<str>,
    value_web: Rc<str>,
    name_web_request: Rc<str>,
    name_express_request: Rc<str>,
    component_http: Rc<str>,
    component_express: Rc<str>,
    component_router: Rc<str>,
    name_router_middleware: Rc<str>,
    name_express_middleware: Rc<str>,
    span_links: Rc<str>,
    events: Rc<str>,
    base_service: Rc<str>,
    process_id: Rc<str>,
    top_level: Rc<str>,
    measured: Rc<str>,
}

impl ConstantKeys {
    fn new() -> Self {
        Self {
            language: Rc::from(META_LANGUAGE),
            component: Rc::from(META_COMPONENT),
            span_kind: Rc::from(META_SPAN_KIND),
            http_method: Rc::from(META_HTTP_METHOD),
            http_url: Rc::from(META_HTTP_URL),
            http_status_code: Rc::from(META_HTTP_STATUS_CODE),
            http_route: Rc::from(META_HTTP_ROUTE),
            integration: Rc::from(META_INTEGRATION),
            trace_id_high: Rc::from(META_TRACE_ID_HIGH),
            error_message: Rc::from(KEY_ERROR_MESSAGE),
            error_type: Rc::from(KEY_ERROR_TYPE),
            error_stack: Rc::from(KEY_ERROR_STACK),
            value_server: Rc::from(VALUE_SERVER),
            value_web: Rc::from(VALUE_WEB),
            name_web_request: Rc::from(NAME_WEB_REQUEST),
            name_express_request: Rc::from(NAME_EXPRESS_REQUEST),
            component_http: Rc::from(COMPONENT_HTTP),
            component_express: Rc::from(COMPONENT_EXPRESS),
            component_router: Rc::from(COMPONENT_ROUTER),
            name_router_middleware: Rc::from(NAME_ROUTER_MIDDLEWARE),
            name_express_middleware: Rc::from(NAME_EXPRESS_MIDDLEWARE),
            span_links: Rc::from(META_SPAN_LINKS),
            events: Rc::from(META_EVENTS),
            base_service: Rc::from(META_BASE_SERVICE),
            process_id: Rc::from(METRIC_PROCESS_ID),
            top_level: Rc::from(METRIC_TOP_LEVEL),
            measured: Rc::from(METRIC_MEASURED),
        }
    }
}

/// One flush batch's finished spans, already encoded.
pub struct Payload {
    pub bytes: Vec<u8>,
    pub trace_count: usize,
}

#[derive(Default)]
struct ProcessInfo {
    /// `config.tags`, parsed from `PROCESS_INFO` once. Applied to spans built from
    /// specialized events, which send no tags of their own.
    tags: Vec<(Rc<str>, Rc<str>)>,
    service: Rc<str>,
    service_lower: String,
    service_lower_shared: Rc<str>,
    env: Rc<str>,
    version: Rc<str>,
    language: Rc<str>,
    pid: u32,
}

/// What a web-server span carries beyond the generic fields. Present only on spans
/// created by `WEB_REQUEST_START`.
#[derive(Default)]
struct WebRequest {
    method: Rc<str>,
    url: Rc<str>,
    route: Rc<str>,
    status_code: u32,
    framework: u32,
}

struct SpanBuilder {
    span_id: u64,
    parent_id: u64,
    start: u64,
    duration: Option<u64>,
    name: Option<Rc<str>>,
    service: Option<Rc<str>>,
    resource: Option<Rc<str>>,
    span_type: Option<Rc<str>>,
    span_kind: Option<Rc<str>>,
    error: i64,
    meta: Vec<(Rc<str>, Rc<str>)>,
    metrics: Vec<(Rc<str>, f64)>,
    links: Vec<Rc<str>>,
    events: Vec<(Rc<str>, u64, Rc<str>)>,
    /// `Some` for a span that came from the specialized web-server events.
    web: Option<Box<WebRequest>>,
}

impl SpanBuilder {
    /// Re-seed a recycled builder. Clearing the vectors keeps their capacity, which is
    /// the whole point of the pool.
    fn reuse(&mut self, span_id: u64, parent_id: u64, start: u64) {
        self.span_id = span_id;
        self.parent_id = parent_id;
        self.start = start;
        self.duration = None;
        self.name = None;
        self.service = None;
        self.resource = None;
        self.span_type = None;
        self.span_kind = None;
        self.error = 0;
        self.meta.clear();
        self.metrics.clear();
        self.links.clear();
        self.events.clear();
        self.web = None;
    }

    /// Release anything the builder still points at before it goes back to the pool, so
    /// a retired span cannot keep a batch's strings alive.
    fn reset(&mut self) {
        self.name = None;
        self.service = None;
        self.resource = None;
        self.span_type = None;
        self.span_kind = None;
        self.meta.clear();
        self.metrics.clear();
        self.links.clear();
        self.events.clear();
        self.web = None;
    }

    fn new(span_id: u64, parent_id: u64, start: u64) -> Self {
        Self {
            span_id,
            parent_id,
            start,
            duration: None,
            name: None,
            service: None,
            resource: None,
            span_type: None,
            span_kind: None,
            error: 0,
            meta: Vec::with_capacity(8),
            metrics: Vec::with_capacity(4),
            links: Vec::new(),
            events: Vec::new(),
            web: None,
        }
    }

    fn set_string_tag(&mut self, key: Rc<str>, value: Rc<str>) {
        match &*key {
            KEY_OPERATION_NAME => self.name = Some(value),
            KEY_SERVICE_NAME => self.service = Some(value),
            KEY_RESOURCE_NAME => self.resource = Some(value),
            KEY_SPAN_TYPE => self.span_type = Some(value),
            KEY_ERROR_MESSAGE | KEY_ERROR_TYPE | KEY_ERROR_STACK => {
                self.error = 1;
                self.meta.push((key, value));
            }
            KEY_SPAN_KIND => {
                self.span_kind = Some(Rc::clone(&value));
                self.meta.push((key, value));
            }
            _ => self.meta.push((key, value)),
        }
    }

    fn set_number_tag(&mut self, key: Rc<str>, value: f64) {
        match &*key {
            KEY_ERROR => self.error = if value == 0.0 { 0 } else { 1 },
            // HACK, mirrored from `span_format.js`: the backend has no numeric
            // status code, so it travels as a meta string.
            KEY_HTTP_STATUS_CODE => self
                .meta
                .push((key, Rc::from(format!("{}", value as i64).as_str()))),
            _ => self.metrics.push((key, value)),
        }
    }
}

struct Segment {
    trace_id: u64,
    /// The wire carries only the low 64 bits of a trace id. The upper half travels as the
    /// `_dd.p.tid` meta tag — written by the JS side on a generic local root, and derived
    /// from this field for a web request, which sends no tags at all.
    trace_id_upper: u64,
    spans: Vec<SpanBuilder>,
    finished: usize,
}

pub struct Assembler {
    keys: ConstantKeys,
    segments: IdMap<Segment>,
    /// Per-span records carry only the subject span id, so routing one to its
    /// segment needs this index.
    span_segments: IdMap<u64>,
    /// Last span a per-span record resolved to, as `(span id, segment id, position in
    /// that segment)`. Runs of records against one span are the norm, not the
    /// exception — it is the same locality the writer's identity elision exploits — so
    /// this turns the common case from two hash lookups plus a scan into one compare.
    /// Positions stay valid because a segment's `spans` only ever grows until the whole
    /// segment is drained, and draining clears this.
    last_span: Option<(u64, u64, usize)>,
    /// Retired builders, kept with their `meta` / `metrics` capacity intact. A span used
    /// to cost two allocations for those vectors and two frees when it left; recycling
    /// makes the steady state allocation-free.
    pool: Vec<SpanBuilder>,
    /// Swapped with a segment's `spans` on every emit so the still-open spans move into
    /// an existing allocation instead of a fresh one.
    scratch: Vec<SpanBuilder>,
    process: ProcessInfo,
    flush_min_spans: usize,
}

impl Assembler {
    pub fn new(flush_min_spans: usize) -> Self {
        Self {
            keys: ConstantKeys::new(),
            segments: IdMap::default(),
            span_segments: IdMap::default(),
            last_span: None,
            pool: Vec::with_capacity(POOL_CAPACITY),
            scratch: Vec::new(),
            process: ProcessInfo::default(),
            flush_min_spans: flush_min_spans.max(1),
        }
    }

    /// Apply a batch's events and encode every segment that completed.
    ///
    /// Encoding happens here rather than in a second pass over an owned intermediate
    /// representation: a finished span is written to bytes and recycled while it is still
    /// in the assembler's hands, so nothing is copied out first.
    ///
    /// `encode` false runs assembly and recycling but skips the byte writing, which is
    /// what `DD_NATIVE_SPANS_ENCODE=0` needs.
    pub fn process(&mut self, events: Vec<Event>, encode: bool) -> Payload {
        // Segments that reached their emit condition during this batch. Collected
        // rather than emitted inline so a segment finishing mid-batch cannot be
        // re-emitted by a later event in the same batch.
        // `(segment id, finished span count)`; the count is filled in after the event
        // loop, once every finish has landed.
        let mut completed: Vec<(u64, usize)> = Vec::new();

        for event in events {
            match event {
                Event::ProcessInfo {
                    service,
                    env,
                    version,
                    language,
                    pid,
                    process_tags,
                } => {
                    // Parsed once per process. A specialized event sends no tags at all,
                    // so these are what stands in for the generic path's
                    // `addTags(config.tags)` on every span.
                    self.process.tags.clear();
                    for entry in process_tags.split('\n') {
                        let Some((key, value)) = entry.split_once('\t') else {
                            continue;
                        };
                        self.process.tags.push((Rc::from(key), Rc::from(value)));
                    }
                    self.process.service_lower = service.to_lowercase();
                    self.process.service_lower_shared = Rc::from(self.process.service_lower.as_str());
                    self.process.service = service;
                    self.process.env = env;
                    self.process.version = version;
                    self.process.language = language;
                    self.process.pid = pid;
                }
                Event::SegmentStart {
                    segment_id,
                    trace_id_upper,
                    trace_id,
                } => {
                    self.segments.insert(
                        segment_id,
                        Segment {
                            trace_id,
                            trace_id_upper,
                            spans: Vec::new(),
                            finished: 0,
                        },
                    );
                }
                Event::SpanStart {
                    segment_id,
                    span_id,
                    parent_id,
                    start,
                } => {
                    let recycled = self.pool.pop();
                    if let Some(segment) = self.segments.get_mut(&segment_id) {
                        match recycled {
                            Some(mut builder) => {
                                builder.reuse(span_id, parent_id, start);
                                segment.spans.push(builder);
                            }
                            None => segment.spans.push(SpanBuilder::new(span_id, parent_id, start)),
                        }
                        self.last_span = Some((span_id, segment_id, segment.spans.len() - 1));
                        self.span_segments.insert(span_id, segment_id);
                    } else if let Some(builder) = recycled {
                        // No such segment: give the builder straight back.
                        self.pool.push(builder);
                    }
                }
                Event::SetTagString { span_id, key, value } => {
                    if let Some(span) = self.span_mut(span_id) {
                        span.set_string_tag(key, value);
                    }
                }
                Event::SetTagNumber { span_id, key, value } => {
                    if let Some(span) = self.span_mut(span_id) {
                        span.set_number_tag(key, value);
                    }
                }
                Event::AddLink { span_id, entry, .. } => {
                    if let Some(span) = self.span_mut(span_id) {
                        span.links.push(entry);
                    }
                }
                Event::AddEvent {
                    span_id,
                    name,
                    time,
                    attributes,
                } => {
                    if let Some(span) = self.span_mut(span_id) {
                        span.events.push((name, time, attributes));
                    }
                }
                Event::WebRequestStart {
                    segment_id,
                    span_id,
                    parent_id,
                    start,
                    method,
                    url,
                } => {
                    // Attaches to whichever segment opened it, the same as `SpanStart`.
                    // Nothing here assumes the request is that segment's root.
                    let mut builder = self
                        .pool
                        .pop()
                        .unwrap_or_else(|| SpanBuilder::new(span_id, parent_id, start));
                    builder.reuse(span_id, parent_id, start);
                    builder.web = Some(Box::new(WebRequest {
                        method,
                        url,
                        ..WebRequest::default()
                    }));
                    if let Some(segment) = self.segments.get_mut(&segment_id) {
                        segment.spans.push(builder);
                        self.last_span = Some((span_id, segment_id, segment.spans.len() - 1));
                        self.span_segments.insert(span_id, segment_id);
                    } else {
                        self.pool.push(builder);
                    }
                }
                Event::WebRequestFinish {
                    span_id,
                    duration,
                    status_code,
                    route,
                    framework,
                } => {
                    let Some(&segment_id) = self.span_segments.get(&span_id) else {
                        continue;
                    };
                    let Some(segment) = self.segments.get_mut(&segment_id) else {
                        continue;
                    };
                    if let Some(span) = segment.spans.iter_mut().find(|span| span.span_id == span_id)
                    {
                        if span.duration.is_none() {
                            span.duration = Some(duration);
                            segment.finished += 1;
                        }
                        // `web.js` treats any 5xx as an error; a thrown error arrives
                        // separately, as `WebRequestError`.
                        if status_code >= 500 {
                            span.error = 1;
                        }
                        if let Some(web) = &mut span.web {
                            web.route = route;
                            web.status_code = status_code;
                            web.framework = framework;
                        }
                    }
                    if segment.finished == segment.spans.len()
                        || segment.finished >= self.flush_min_spans
                    {
                        completed.push((segment_id, 0));
                    }
                }
                Event::MiddlewareStart {
                    segment_id,
                    span_id,
                    parent_id,
                    start,
                    resource,
                    framework,
                } => {
                    let express = framework == MIDDLEWARE_EXPRESS;
                    let name = Rc::clone(if express {
                        &self.keys.name_express_middleware
                    } else {
                        &self.keys.name_router_middleware
                    });
                    let component = Rc::clone(if express {
                        &self.keys.component_express
                    } else {
                        &self.keys.component_router
                    });
                    let component_key = Rc::clone(&self.keys.component);
                    let integration_key = Rc::clone(&self.keys.integration);

                    let mut builder = self
                        .pool
                        .pop()
                        .unwrap_or_else(|| SpanBuilder::new(span_id, parent_id, start));
                    builder.reuse(span_id, parent_id, start);
                    builder.name = Some(name);
                    builder.resource = Some(resource);
                    builder.meta.push((component_key, Rc::clone(&component)));
                    builder.meta.push((integration_key, component));

                    if let Some(segment) = self.segments.get_mut(&segment_id) {
                        segment.spans.push(builder);
                        self.last_span = Some((span_id, segment_id, segment.spans.len() - 1));
                        self.span_segments.insert(span_id, segment_id);
                    } else {
                        self.pool.push(builder);
                    }
                }
                Event::SpanError {
                    span_id,
                    message,
                    error_type,
                    stack,
                } => {
                    // Cloned up front: `span_mut` borrows `self` mutably for the rest
                    // of the block.
                    let message_key = Rc::clone(&self.keys.error_message);
                    let type_key = Rc::clone(&self.keys.error_type);
                    let stack_key = Rc::clone(&self.keys.error_stack);
                    if let Some(span) = self.span_mut(span_id) {
                        span.error = 1;
                        if !message.is_empty() {
                            span.meta.push((message_key, message));
                        }
                        if !error_type.is_empty() {
                            span.meta.push((type_key, error_type));
                        }
                        if !stack.is_empty() {
                            span.meta.push((stack_key, stack));
                        }
                    }
                }
                Event::Finish { span_id, duration } => {
                    let Some(&segment_id) = self.span_segments.get(&span_id) else {
                        continue;
                    };
                    let Some(segment) = self.segments.get_mut(&segment_id) else {
                        continue;
                    };
                    if let Some(span) = segment.spans.iter_mut().find(|span| span.span_id == span_id) {
                        if span.duration.is_none() {
                            span.duration = Some(duration);
                            segment.finished += 1;
                        }
                    }
                    if segment.finished == segment.spans.len() || segment.finished >= self.flush_min_spans {
                        completed.push((segment_id, 0));
                    }
                }
            }
        }

        // Resolve each completed segment's span count once, up front: it both sizes the
        // payload — so the buffer never reallocates mid-batch, which for 40 MB would be a
        // dozen doublings and as many megabytes of memcpy — and saves `emit_segment` a
        // second lookup for the same segment. `segment.finished` is already the count, so
        // there is no scan.
        let mut span_total = 0;
        completed.retain_mut(|entry| {
            let Some(segment) = self.segments.get(&entry.0) else {
                return false;
            };
            // A segment can reach the emit condition more than once in a batch (the
            // `flushMinSpans` threshold); only the first entry has spans to emit.
            if segment.finished == 0 {
                return false;
            }
            entry.1 = segment.finished;
            span_total += segment.finished;
            true
        });

        let mut bytes = Vec::with_capacity(span_total * encode::ESTIMATED_SPAN_BYTES + 1024);
        encode::begin_payload(&mut bytes);

        let mut trace_count = 0;
        for (segment_id, finished) in completed {
            if self.emit_segment(&mut bytes, segment_id, finished, encode) {
                trace_count += 1;
            }
        }

        encode::finish_payload(&mut bytes, trace_count as u32);

        Payload { bytes, trace_count }
    }

    fn span_mut(&mut self, span_id: u64) -> Option<&mut SpanBuilder> {
        if let Some((cached_span_id, segment_id, position)) = self.last_span {
            if cached_span_id == span_id {
                return self.segments.get_mut(&segment_id)?.spans.get_mut(position);
            }
        }

        let segment_id = *self.span_segments.get(&span_id)?;
        let segment = self.segments.get_mut(&segment_id)?;
        let position = segment.spans.iter().position(|span| span.span_id == span_id)?;
        self.last_span = Some((span_id, segment_id, position));
        segment.spans.get_mut(position)
    }

    /// Drain a segment's finished spans into a chunk, leaving any still-open span
    /// behind as the segment's remaining started set — the same split
    /// `SpanProcessor._erase` does with its `active` list.
    /// Write a completed segment's finished spans and leave its still-open ones behind —
    /// the same split `SpanProcessor._erase` makes with its `active` list.
    ///
    /// The segment's span vector is moved out for the duration so the borrow checker
    /// allows reading `self.process` and `self.keys` while mutating the spans, and it is
    /// swapped with a reusable scratch vector rather than replaced by a fresh one.
    fn emit_segment(
        &mut self,
        out: &mut Vec<u8>,
        segment_id: u64,
        finished: usize,
        encode: bool,
    ) -> bool {
        // An empty vector with capacity, to receive whichever spans are still open.
        let mut open = std::mem::take(&mut self.scratch);

        let (mut spans, trace_id, trace_id_upper) = match self.segments.get_mut(&segment_id) {
            Some(segment) => {
                segment.finished = 0;
                (
                    std::mem::take(&mut segment.spans),
                    segment.trace_id,
                    segment.trace_id_upper,
                )
            }
            None => {
                self.scratch = open;
                return false;
            }
        };

        if encode {
            out.reserve(finished * encode::ESTIMATED_SPAN_BYTES);
            encode::write_trace_header(out, finished as u32);
        }

        for mut span in spans.drain(..) {
            if span.duration.is_none() {
                open.push(span);
                continue;
            }
            self.span_segments.remove(&span.span_id);
            if encode {
                self.write_span(out, &mut span, segment_id, trace_id, trace_id_upper);
            }
            if self.pool.len() < POOL_CAPACITY {
                span.reset();
                self.pool.push(span);
            }
        }

        // `spans` is empty now and keeps its capacity, so it becomes the next scratch.
        self.scratch = spans;
        self.last_span = None;

        if open.is_empty() {
            self.segments.remove(&segment_id);
        } else if let Some(segment) = self.segments.get_mut(&segment_id) {
            segment.spans = open;
        }

        true
    }

    /// Normalise and write one span. This is where the defaults land, with no
    /// special-casing: a per-span `service.name` override arrived as an ordinary
    /// `SET_TAG_STRING`, and anything absent falls back to the process-level value from
    /// `PROCESS_INFO`.
    fn write_span(
        &self,
        out: &mut Vec<u8>,
        span: &mut SpanBuilder,
        segment_id: u64,
        trace_id: u64,
        trace_id_upper: u64,
    ) {
        // A web-server span arrives with no tags at all: its whole tag set follows from
        // being a web-server span, so it is reconstituted here rather than sent.
        if span.web.is_some() {
            self.expand_web_request(span, trace_id_upper);
        }

        // `config.tags` — `runtime-id`, the remote-config client id, `service`, `env`,
        // `version` and any global tag the user set. These used to be re-tagged onto every
        // span from JS; they now arrive once, on `PROCESS_INFO`, and are applied here.
        //
        // Spliced in *front* of the span's own entries because deduplication keeps the
        // last write: a per-span tag has to beat the global of the same name, which is the
        // order `addTags(config.tags)` then `addTags(options.tags)` produced.
        if !self.process.tags.is_empty() {
            // Unified service tagging: a span that overrode the service does not inherit
            // the global version.
            let inherits_version = span
                .service
                .as_deref()
                .is_none_or(|service| service.eq_ignore_ascii_case(&self.process.service_lower));
            span.meta.splice(
                0..0,
                self.process
                    .tags
                    .iter()
                    .filter(|(key, _)| inherits_version || &**key != META_VERSION)
                    .map(|(key, value)| (Rc::clone(key), Rc::clone(value))),
            );
        }

        // The derived entries go into the span's own maps so the encoder's
        // last-write-wins deduplication still lets them override a user tag of the same
        // name, which is the order `extractTags` produces.
        span.meta
            .push((Rc::clone(&self.keys.language), Rc::clone(&self.process.language)));
        span.metrics
            .push((Rc::clone(&self.keys.process_id), self.process.pid as f64));

        if !span.links.is_empty() {
            let mut serialized = String::from("[");
            for (index, entry) in span.links.iter().enumerate() {
                if index > 0 {
                    serialized.push(',');
                }
                serialized.push_str(entry);
            }
            serialized.push(']');
            span.meta
                .push((Rc::clone(&self.keys.span_links), Rc::from(serialized.as_str())));
        }

        if !span.events.is_empty() {
            let serialized = serialize_events(&span.events);
            span.meta
                .push((Rc::clone(&self.keys.events), Rc::from(serialized.as_str())));
        }

        // `normalizeSpan`: an absent or empty name and service fall back to their
        // placeholders, resource falls back to the name, and all three plus the type are
        // capped at 100 characters. Truncation is a shorter borrow, not a new string.
        let name = match span.name.as_deref() {
            Some(value) if !value.is_empty() => truncate(value, MAX_NAME_LENGTH),
            _ => DEFAULT_SPAN_NAME,
        };
        let resource = match span.resource.as_deref() {
            Some(value) if !value.is_empty() => value,
            _ => name,
        };
        let service = match span.service.as_deref() {
            Some(value) if !value.is_empty() => truncate(value, MAX_SERVICE_LENGTH),
            _ if !self.process.service.is_empty() => &self.process.service,
            _ => DEFAULT_SERVICE_NAME,
        };
        let span_type = match span.span_type.as_deref() {
            Some(value) => truncate(value, MAX_TYPE_LENGTH),
            None => "",
        };

        if !self.process.service_lower.is_empty()
            && !service.eq_ignore_ascii_case(&self.process.service_lower)
        {
            span.meta.push((
                Rc::clone(&self.keys.base_service),
                Rc::clone(&self.process.service_lower_shared),
            ));
        }

        // `extractRootTags` gates on being the chunk's first span *and* having no parent,
        // so a segment rooted on a remote parent gets no top-level marker.
        if span.span_id == segment_id && span.parent_id == 0 {
            span.metrics.push((Rc::clone(&self.keys.top_level), 1.0));
        }

        if let Some(kind) = &span.span_kind {
            if &**kind != "internal" {
                span.metrics.push((Rc::clone(&self.keys.measured), 1.0));
            }
        }

        encode::write_span(
            out,
            &encode::SpanWire {
                trace_id,
                span_id: span.span_id,
                parent_id: span.parent_id,
                service,
                name,
                resource,
                span_type,
                error: span.error,
                start: span.start,
                duration: span.duration.unwrap_or(0),
                meta: &span.meta,
                metrics: &span.metrics,
            },
        );
    }
}

/// Everything a web-server span carries that the wire did not have to send. The four
/// values it did send — method, URL, status, route — plus one framework word are enough,
/// because the rest is the same on every web request: kind, type, component, integration,
/// and the process-level service / env / version that a generic span picks up from
/// `config.tags` one `setTag` at a time.
impl Assembler {
    fn expand_web_request(&self, span: &mut SpanBuilder, trace_id_upper: u64) {
        let web = span.web.as_ref().expect("caller checked");
        let express = web.framework == FRAMEWORK_EXPRESS;

        span.name = Some(Rc::clone(if express {
            &self.keys.name_express_request
        } else {
            &self.keys.name_web_request
        }));
        span.span_type = Some(Rc::clone(&self.keys.value_web));
        // `addResourceTag`: the method, joined with the route when one matched.
        span.resource = Some(if web.route.is_empty() {
            Rc::clone(&web.method)
        } else {
            Rc::from(format!("{} {}", web.method, web.route).as_str())
        });
        // `span.kind` is always `server`, which is also what makes the span measured.
        span.span_kind = Some(Rc::clone(&self.keys.value_server));

        let component = if express {
            &self.keys.component_express
        } else {
            &self.keys.component_http
        };
        span.meta
            .push((Rc::clone(&self.keys.component), Rc::clone(component)));
        span.meta
            .push((Rc::clone(&self.keys.integration), Rc::clone(component)));
        span.meta.push((
            Rc::clone(&self.keys.span_kind),
            Rc::clone(&self.keys.value_server),
        ));
        span.meta
            .push((Rc::clone(&self.keys.http_method), Rc::clone(&web.method)));
        span.meta
            .push((Rc::clone(&self.keys.http_url), Rc::clone(&web.url)));
        span.meta.push((
            Rc::clone(&self.keys.http_status_code),
            Rc::from(web.status_code.to_string().as_str()),
        ));
        if !web.route.is_empty() {
            span.meta
                .push((Rc::clone(&self.keys.http_route), Rc::clone(&web.route)));
        }

        // The upper half of the 128-bit trace id. A generic span has the JS side write
        // this as a tag on every local root; here it is derived from the id the segment
        // already carries.
        if trace_id_upper != 0 {
            span.meta.push((
                Rc::clone(&self.keys.trace_id_high),
                Rc::from(format!("{:016x}", trace_id_upper).as_str()),
            ));
        }

    }
}

/// Cap `value` at `limit` characters. The byte length is a free upper bound on the
/// character count, so a string that cannot possibly need truncating — which is all of
/// them in practice — costs one integer compare and no scan.
///
/// JS slices by UTF-16 code unit; this slices by character, so the two differ only for
/// a name carrying astral-plane text right at the 100-character boundary.
fn truncate(value: &str, limit: usize) -> &str {
    if value.len() <= limit {
        return value;
    }
    match value.char_indices().nth(limit) {
        Some((end, _)) => &value[..end],
        None => value,
    }
}

/// The `meta.events` JSON, matching `stringifySpanEvents` in `encode/0.4.js`: the
/// wire key is `time_unix_nano`, and an empty attribute set is omitted rather than
/// serialized as `{}`.
fn serialize_events(events: &[(Rc<str>, u64, Rc<str>)]) -> String {
    let mut result = String::from("[");
    for (index, (name, time, attributes)) in events.iter().enumerate() {
        if index > 0 {
            result.push(',');
        }
        result.push_str("{\"name\":");
        push_json_string(&mut result, name);
        result.push_str(",\"time_unix_nano\":");
        result.push_str(&time.to_string());
        if !attributes.is_empty() {
            result.push_str(",\"attributes\":");
            result.push_str(attributes);
        }
        result.push('}');
    }
    result.push(']');
    result
}

fn push_json_string(out: &mut String, value: &str) {
    out.push('"');
    for character in value.chars() {
        match character {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            control if control < ' ' => {
                out.push_str(&format!("\\u{:04x}", control as u32));
            }
            other => out.push(other),
        }
    }
    out.push('"');
}
