name: Install branch-diff
description: Install branch-diff
inputs:
  token:
    description: "The GitHub token to use for diff operations."
    required: true
runs:
  using: composite
  steps:
    - uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
      with:
        path: ~/.npm
        key: ${{ github.workflow }}-branch-diff-3.1.1
    - run: npm i -g branch-diff@3.1.1
      shell: bash
    - run: |
        mkdir -p ~/.config/changelog-maker
        echo "{\"token\":\"${{ inputs.token }}\",\"user\":\"${{ github.actor }}\"}" > ~/.config/changelog-maker/config.json
        git config user.name ${{ github.actor }}
        git config user.email ${{ github.actor }}@users.noreply.github.com
      shell: bash
