name: Push JUnit reports
description: Upload any *junit.xml files to Datadog Test Optimization
inputs:
  datadog-ci-version:
    description: Version of datadog-ci to use (e.g. 4.0.2, no leading "v")
    required: false
    default: '4.0.2'
  site:
    description: Datadog site (datadoghq.com, datadoghq.eu, ...)
    required: false
    default: 'datadoghq.com'
  pattern:
    description: Glob for JUnit files
    required: false
    default: '**/*junit.xml'
  verbose:
    description: Pass --verbose to datadog-ci
    required: false
    default: 'true'
  dd-api-key:
    description: Datadog API key
    required: true

runs:
  using: node20
  main: dist/main/index.js
  post: dist/post/index.js
