'use strict'

module.exports = {
  ASM_ACTIVATION: 1n << 1n,
  ASM_IP_BLOCKING: 1n << 2n,
  ASM_DD_RULES: 1n << 3n,
  ASM_EXCLUSIONS: 1n << 4n,
  ASM_REQUEST_BLOCKING: 1n << 5n,
  ASM_RESPONSE_BLOCKING: 1n << 6n,
  ASM_USER_BLOCKING: 1n << 7n,
  ASM_CUSTOM_RULES: 1n << 8n,
  ASM_CUSTOM_BLOCKING_RESPONSE: 1n << 9n,
  ASM_TRUSTED_IPS: 1n << 10n,
  ASM_API_SECURITY_SAMPLE_RATE: 1n << 11n, // deprecated
  ASM_PROCESSOR_OVERRIDES: 1n << 16n,
  ASM_CUSTOM_DATA_SCANNERS: 1n << 17n,
  ASM_EXCLUSION_DATA: 1n << 18n,
  ASM_RASP_SQLI: 1n << 21n,
  ASM_RASP_LFI: 1n << 22n,
  ASM_RASP_SSRF: 1n << 23n,
  ASM_RASP_SHI: 1n << 24n,
  ASM_AUTO_USER_INSTRUM_MODE: 1n << 31n,
  ASM_ENDPOINT_FINGERPRINT: 1n << 32n,
  ASM_SESSION_FINGERPRINT: 1n << 33n,
  ASM_NETWORK_FINGERPRINT: 1n << 34n,
  ASM_HEADER_FINGERPRINT: 1n << 35n,
  ASM_RASP_CMDI: 1n << 37n,
  ASM_DD_MULTICONFIG: 1n << 42n,
  ASM_TRACE_TAGGING_RULES: 1n << 43n,
  ASM_EXTENDED_DATA_COLLECTION: 1n << 44n,
  APM_TRACING_MULTICONFIG: 1n << 45n,
  FFE_FLAG_CONFIGURATION_RULES: 1n << 46n,
  SDK_CONFIGURATION: 1n << 49n,
  /*
    DO NOT ADD ARBITRARY CAPABILITIES IN YOUR CODE
    UNLESS THEY ARE ALREADY DEFINED IN THE BACKEND SOURCE OF TRUTH
    DOING SO TRIGGERS BACKEND ALERTS
  */
}
