module.exports = {
  COMMAND_INJECTION: 'COMMAND_INJECTION',
  INSECURE_COOKIE: 'INSECURE_COOKIE',
  LDAP_INJECTION: 'LDAP_INJECTION',
  PATH_TRAVERSAL: 'PATH_TRAVERSAL',
  SQL_INJECTION: 'SQL_INJECTION',
  SSRF: 'SSRF',
  WEAK_CIPHER: 'WEAK_CIPHER',
  WEAK_HASH: 'WEAK_HASH'
}
