module.exports = {
  COMMAND_INJECTION: 'COMMAND_INJECTION',
  INSECURE_COOKIE: 'INSECURE_COOKIE',
  LDAP_INJECTION: 'LDAP_INJECTION',
  NO_HTTP_ONLY_COOKIE: 'NO_HTTP_ONLY_COOKIE',
  PATH_TRAVERSAL: 'PATH_TRAVERSAL',
  SQL_INJECTION: 'SQL_INJECTION',
  SSRF: 'SSRF',
  UNVALIDATED_REDIRECT: 'UNVALIDATED_REDIRECT',
  WEAK_CIPHER: 'WEAK_CIPHER',
  WEAK_HASH: 'WEAK_HASH'
}
