module.exports = {
  WEAK_HASH: 'WEAK_HASH',
  WEAK_CIPHER: 'WEAK_CIPHER',
  SQL_INJECTION: 'SQL_INJECTION',
  PATH_TRAVERSAL: 'PATH_TRAVERSAL',
  COMMAND_INJECTION: 'COMMAND_INJECTION',
  LDAP_INJECTION: 'LDAP_INJECTION',
  INSECURE_COOKIE: 'INSECURE_COOKIE'
}
