// AUTO-GENERATED by dd-compile
// Orchestrion rewriter handles the actual instrumentation via JSON config.
// This file registers the module hooks for the rewriter to process.

'use strict'

const { addHook, getHooks } = require('./helpers/instrument')

for (const hook of getHooks('bullmq')) {
  addHook(hook, exports => exports)
}
