// AUTO-GENERATED by dd-compile from mysql.analysis.json
// To customize instrumentation behavior, edit this file directly.
// Re-running dd-compile will show a diff but won't overwrite without confirmation.

'use strict'

const { addHook } = require('./helpers/instrument')
const shimmer = require('../../datadog-shimmer')
const { createWrapper } = require('./helpers/wrappers')

addHook({ name: 'mysql', file: 'lib/Connection.js', versions: ['^2.18.1'] }, (exports) => {
  const PatchedClass = exports.default || exports['Connection'] || exports
  if (PatchedClass && PatchedClass.prototype && PatchedClass.prototype['query']) {
    shimmer.wrap(PatchedClass.prototype, 'query', (original) => {
      const wrapper = createWrapper('apm:mysql:connection:query', 'traceCallback')(original)
      return function (...args) {
        const hasCallback = args.length > 0 && typeof args[args.length - 1] === 'function'
        if (!hasCallback) {
          return original.apply(this, args)
        }
        return wrapper.apply(this, args)
      }
    })
  }
  return exports
})

addHook({ name: 'mysql', file: 'lib/Pool.js', versions: ['^2.18.1'] }, (exports) => {
  const PatchedClass = exports.default || exports['Pool'] || exports
  if (PatchedClass && PatchedClass.prototype && PatchedClass.prototype['query']) {
    shimmer.wrap(PatchedClass.prototype, 'query', (original) => {
      const wrapper = createWrapper('apm:mysql:pool:query', 'traceCallback')(original)
      return function (...args) {
        const hasCallback = args.length > 0 && typeof args[args.length - 1] === 'function'
        if (!hasCallback) {
          return original.apply(this, args)
        }
        return wrapper.apply(this, args)
      }
    })
  }
  return exports
})

addHook({ name: 'mysql', file: 'lib/Connection.js', versions: ['^2.18.1'] }, (exports) => {
  const PatchedClass = exports.default || exports['Connection'] || exports
  if (PatchedClass && PatchedClass.prototype && PatchedClass.prototype['beginTransaction']) {
    shimmer.wrap(PatchedClass.prototype, 'beginTransaction', createWrapper('apm:mysql:connection:begintransaction', 'traceCallback'))
  }
  return exports
})

addHook({ name: 'mysql', file: 'lib/Connection.js', versions: ['^2.18.1'] }, (exports) => {
  const PatchedClass = exports.default || exports['Connection'] || exports
  if (PatchedClass && PatchedClass.prototype && PatchedClass.prototype['commit']) {
    shimmer.wrap(PatchedClass.prototype, 'commit', createWrapper('apm:mysql:connection:commit', 'traceCallback'))
  }
  return exports
})

addHook({ name: 'mysql', file: 'lib/Connection.js', versions: ['^2.18.1'] }, (exports) => {
  const PatchedClass = exports.default || exports['Connection'] || exports
  if (PatchedClass && PatchedClass.prototype && PatchedClass.prototype['rollback']) {
    shimmer.wrap(PatchedClass.prototype, 'rollback', createWrapper('apm:mysql:connection:rollback', 'traceCallback'))
  }
  return exports
})
