name: Node.js
description: Install the version of Node.js matching the input identifier
inputs:
  version:
    description: "Version identifier of the version to use."
    required: false
    default: 'latest'
runs:
  using: composite
  steps:
    - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
      with:
        node-version: ${{ inputs.version == 'eol' && '16' || inputs.version == 'oldest' && '18' || inputs.version == 'maintenance' && '20' || inputs.version == 'active' && '22' || inputs.version == 'latest' && (env.RUN_NIGHTLY && format('{0}-{1}', env.RUN_NIGHTLY, '-nightly') || '24') || inputs.version }}
        check-latest: true
        registry-url: ${{ inputs.registry-url || 'https://registry.npmjs.org' }}
