name: Node.js
description: Install the version of Node.js matching the input identifier
inputs:
  version:
    description: "Version identifier of the version to use."
    required: false
    default: 'latest'
runs:
  using: composite
  steps:
    - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
      with:
        node-version: ${{
          inputs.version == 'eol' && '16' ||
          inputs.version == 'oldest' && '18' ||
          inputs.version == 'maintenance' && '20' ||
          inputs.version == 'active' && '22' ||
          inputs.version == 'latest' && (env.LATEST_VERSION || '24') ||
          inputs.version }}
        check-latest: true
        registry-url: ${{ inputs.registry-url || 'https://registry.npmjs.org' }}
    - uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2.0.2
      with:
        bun-version: "1.3.1"
