name: Node.js
description: Install the version of Node.js matching the input identifier
inputs:
  version:
    description: "Version identifier of the version to use."
    required: false
    default: 'latest'
runs:
  using: composite
  steps:
    - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
      with:
        node-version: ${{
          inputs.version == 'eol' && '16' ||
          inputs.version == 'oldest' && '18' ||
          inputs.version == 'maintenance' && '20' ||
          inputs.version == 'active' && '22' ||
          inputs.version == 'latest' && (env.LATEST_VERSION || '24') ||
          inputs.version }}
        check-latest: true
        registry-url: ${{ inputs.registry-url || 'https://registry.npmjs.org' }}
    - uses: oven-sh/setup-bun@b7a1c7ccf290d58743029c4f6903da283811b979 # v2.1.0
      with:
        bun-version: "1.3.1"
