apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: datadog-agent
  namespace: default
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: datadog-agent
  template:
    metadata:
      name: datadog-agent
      labels:
        app: datadog-agent
    spec:
      affinity: {}
      containers:
      - command:
        - ddapm-test-agent
        env:
        - name: SNAPSHOT_CI
          value: "0"
        - name: PORT
          value: "18126"
        image: ghcr.io/datadog/dd-apm-test-agent/ddapm-test-agent:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 15
          periodSeconds: 15
          successThreshold: 1
          tcpSocket:
            port: 18126
          timeoutSeconds: 5
        name: trace-agent
        ports:
        - containerPort: 18126
          hostPort: 18126
          name: traceport
          protocol: TCP
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsUser: 0
      terminationGracePeriodSeconds: 30
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 10%
    type: RollingUpdate
