name: Get Datadog API key
description: Exchange GitHub OIDC token for a Datadog API key via dd-sts.

outputs:
  api_key:
    description: "Datadog API key"
    value: ${{ steps.dd-sts.outputs.api_key }}

runs:
  using: composite
  steps:
    - name: Get Datadog API key
      id: dd-sts
      uses: DataDog/dd-sts-action@1f350ca511be980515cf08b0bd64182b9c6e5d32 # v1.0.3
      with:
        policy: dd-trace-js-api-key
