// AUTO-GENERATED by dd-compile from neo4j-driver.analysis.json
// To customize tag extraction, edit this file directly.
// Re-running dd-compile will show a diff but won't overwrite without confirmation.

'use strict'

function sessionRunClient (ctx) {
  const query = ctx.args?.[0]
  return {
    operation: 'run',
    resource: typeof query === 'string' ? query : 'run',
    meta: {
      component: 'neo4j-driver',
      'span.kind': 'client',
      'db.type': 'neo4j',
      'db.statement': typeof query === 'string' ? query : (query?.text || 'run')
    }
  }
}

function transactionRunClient (ctx) {
  const query = ctx.args?.[0]
  return {
    operation: 'run',
    resource: typeof query === 'string' ? query : 'run',
    meta: {
      component: 'neo4j-driver',
      'span.kind': 'client',
      'db.type': 'neo4j',
      'db.statement': typeof query === 'string' ? query : (query?.text || 'run')
    }
  }
}

function sessionExecutereadClient (ctx) {
  return {
    operation: 'executeRead',
    resource: 'executeRead',
    meta: {
      component: 'neo4j-driver',
      'span.kind': 'client',
      'db.type': 'neo4j',
      'db.name': 'neo4j',
      'db.user': 'neo4j',
      'db.statement': 'executeRead',
      'db.stream': '0'
    },
    metrics: {
      'db.pid': 0
    }
  }
}

function sessionExecutewriteClient (ctx) {
  return {
    operation: 'executeWrite',
    resource: 'executeWrite',
    meta: {
      component: 'neo4j-driver',
      'span.kind': 'client',
      'db.type': 'neo4j',
      'db.statement': 'executeWrite'
    }
  }
}

function transactionCommitClient (ctx) {
  return {
    operation: 'commit',
    resource: 'commit',
    meta: {
      component: 'neo4j-driver',
      'span.kind': 'client',
      'db.type': 'neo4j'
    }
  }
}

function transactionRollbackClient (ctx) {
  return {
    operation: 'rollback',
    resource: 'rollback',
    meta: {
      component: 'neo4j-driver',
      'span.kind': 'client',
      'db.type': 'neo4j'
    }
  }
}

module.exports = {
  'tracing:apm:neo4j-driver:session:run': sessionRunClient,
  'tracing:apm:neo4j-driver:transaction:run': transactionRunClient,
  'tracing:apm:neo4j-driver:session:executeread': sessionExecutereadClient,
  'tracing:apm:neo4j-driver:session:executewrite': sessionExecutewriteClient,
  'tracing:apm:neo4j-driver:transaction:commit': transactionCommitClient,
  'tracing:apm:neo4j-driver:transaction:rollback': transactionRollbackClient
}
