// AUTO-GENERATED by dd-compile from neo4j-driver.analysis.json
// To customize plugin behavior, edit this file directly.
// Re-running dd-compile will show a diff but won't overwrite without confirmation.

'use strict'

const DatabasePlugin = require('../../dd-trace/src/plugins/database')
const Extractors = require('./extractors')

class Neo4jDriverClientPlugin extends DatabasePlugin {
  static get id () {
    return 'neo4j-driver'
  }

  constructor (...args) {
    super(...args)
    this.subscribe()
  }

  subscribe () {
    // Register operations for each additional instrumented operation, auto-handles subscriptions
    this.registerOperation('tracing:apm:neo4j-driver:session:run')
    this.registerOperation('tracing:apm:neo4j-driver:transaction:run')
    this.registerOperation('tracing:apm:neo4j-driver:session:executeread')
    this.registerOperation('tracing:apm:neo4j-driver:session:executewrite')
    this.registerOperation('tracing:apm:neo4j-driver:transaction:commit')
    this.registerOperation('tracing:apm:neo4j-driver:transaction:rollback')
  }

  bindStart (ctx, channel) {
    const options = Extractors[channel]?.(ctx)
    if (!options) return ctx.currentStore

    this.startSpan(`${this.constructor.id}.${options.operation}`, options, ctx)
    return ctx.currentStore
  }

  asyncEnd (ctx) {
    this.finish(ctx)
  }

  error (ctx, channelName) {
    const error = ctx?.error || ctx
    if (error) {
      this.addError(error)
    }
  }

  finish (ctx) {
    const span = ctx?.currentStore?.span
    if (span) {
      super.finish(ctx)
    }
  }
}

module.exports = Neo4jDriverClientPlugin
