name: Node.js Newst Maintenance LTS
description: Install the newest Maintenance LTS version of Node.js
runs:
  using: composite
  steps:
    - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
      with:
        cache: yarn
        node-version: '20'
