name: Node.js Newst Maintenance LTS
description: Install the newest Maintenance LTS version of Node.js
runs:
  using: composite
  steps:
    - uses: ./.github/actions/node
      with:
        version: maintenance
