name: Node.js Newst Maintenance LTS
description: Install the newest Maintenance LTS version of Node.js
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
