// AUTO-GENERATED by dd-compile from polka.analysis.json
// To customize tag extraction, edit this file directly.
// Re-running dd-compile will show a diff but won't overwrite without confirmation.

'use strict'

function polkaHandlerServer (ctx) {
  const tags = {
    'component': 'polka',
    'span.kind': 'server'
  }

  // Extract req, res from context arguments
  // handler signature: handler(req, res, info)
  const args = ctx.arguments || ctx.args || []
  const req = args[0]
  const res = args[1]

  if (req) {
    // Extract HTTP method
    if (req.method) {
      tags['http.method'] = req.method
    }

    // Extract HTTP URL
    if (req.url) {
      tags['http.url'] = req.url
    }

    // Extract route pattern (attached by instrumentation)
    if (req._ddRoute) {
      tags['http.route'] = req._ddRoute
    }

    // Extract user agent
    if (req.headers && req.headers['user-agent']) {
      tags['http.useragent'] = req.headers['user-agent']
    }
  }

  // Note: http.status_code is set later in the response 'finish' event
  // in the plugin's polkaHandlerStart method, not here in the extractor

  // Build resource name from method and route
  const method = tags['http.method'] || 'HTTP'
  const route = tags['http.route'] || tags['http.url'] || 'handler'
  tags['resource.name'] = `${method} ${route}`

  return tags
}

module.exports = {
  'polkaHandlerServer': polkaHandlerServer
}
