'use strict'

// targets.json is generated by scripts/generate-rewriter-targets.js from ./instrumentation-registry.
const targets = require('./targets.json')
const rewriteTargetNames = new Set(Object.values(targets))

const NODE_MODULES = '/node_modules/'

/**
 * @typedef {object} RewriteTarget
 * @property {string} moduleName
 * @property {string} filePath
 * @property {boolean} [activate]
 */

/**
 * @param {string} filename
 * @returns {RewriteTarget|undefined}
 */
function getRewriteTarget (filename) {
  const nodeModulesIndex = filename.lastIndexOf(NODE_MODULES)
  if (nodeModulesIndex === -1) return

  const modulePath = filename.slice(nodeModulesIndex + NODE_MODULES.length)
  if (!Object.hasOwn(targets, modulePath)) return
  const moduleName = targets[modulePath]
  if (typeof moduleName !== 'string') return
  const activate = isRewriteActivationEnabled(moduleName)

  const rewriteTarget = {
    moduleName,
    filePath: modulePath.slice(moduleName.length + 1),
  }
  if (activate) rewriteTarget.activate = true
  return rewriteTarget
}

function getRewriteTargetNames () {
  return rewriteTargetNames.values()
}

/**
 * @param {string} name
 */
function isRewriteTargetName (name) {
  return rewriteTargetNames.has(name)
}

/**
 * @param {string} moduleName
 */
function isRewriteActivationEnabled (moduleName) {
  // Keep target-name-only consumers from loading every instrumentation descriptor.
  return require('./instrumentation-registry').isRewriteActivationEnabled(moduleName)
}

module.exports = { getRewriteTarget, getRewriteTargetNames, isRewriteActivationEnabled, isRewriteTargetName }
