'use strict'

// targets.json is generated by scripts/generate-rewriter-targets.js from ./instrumentation-registry.
const targets = require('./targets.json')
const patternSources = require('./target-patterns.json')
/** @type {Record<string, RegExp[]>} */
const patterns = Object.create(null)
for (const [name, sources] of Object.entries(patternSources)) {
  const packagePatterns = patterns[name] = []
  for (const source of sources) packagePatterns.push(new RegExp(source))
}
const rewriteTargetNames = new Set([...Object.values(targets), ...Object.keys(patterns)])

const NODE_MODULES = '/node_modules/'

/**
 * @typedef {object} RewriteTarget
 * @property {string} moduleName
 * @property {string} filePath
 * @property {string} [activationName]
 */

/**
 * @param {string} filename
 * @returns {RewriteTarget|undefined}
 */
function getRewriteTarget (filename) {
  const nodeModulesIndex = filename.lastIndexOf(NODE_MODULES)
  if (nodeModulesIndex === -1) return

  const modulePath = filename.slice(nodeModulesIndex + NODE_MODULES.length)
  let moduleName = targets[modulePath]
  if (typeof moduleName !== 'string') {
    const firstSlash = modulePath.indexOf('/')
    if (firstSlash === -1) return
    const packageEnd = modulePath[0] === '@' ? modulePath.indexOf('/', firstSlash + 1) : firstSlash
    if (packageEnd === -1) return
    moduleName = modulePath.slice(0, packageEnd)
    if (!Object.hasOwn(patterns, moduleName)) return
    const packagePatterns = patterns[moduleName]
    const filePath = modulePath.slice(packageEnd + 1)
    let matched = false
    for (const pattern of packagePatterns) {
      if (pattern.test(filePath)) {
        matched = true
        break
      }
    }
    if (!matched) return
  }
  const activationName = getRewriteActivationName(moduleName)

  const rewriteTarget = {
    moduleName,
    filePath: modulePath.slice(moduleName.length + 1),
  }
  if (activationName) rewriteTarget.activationName = activationName
  return rewriteTarget
}

function getRewriteTargetNames () {
  return rewriteTargetNames.values()
}

/**
 * @param {string} name
 */
function isRewriteTargetName (name) {
  return rewriteTargetNames.has(name)
}

/**
 * @param {string} moduleName
 */
function getRewriteActivationName (moduleName) {
  // Keep target-name-only consumers from loading every instrumentation descriptor.
  return require('./instrumentation-registry').getRewriteActivationName(moduleName)
}

module.exports = { getRewriteActivationName, getRewriteTarget, getRewriteTargetNames, isRewriteTargetName }
