'use strict'

// targets.json is generated by scripts/generate-rewriter-targets.js from ./instrumentation-registry.
const targets = require('./targets.json')
const targetPatterns = require('./target-patterns.json').map(({ name, source, flags, sourceMatch }) => ({
  name,
  pattern: new RegExp(source, flags),
  sourceMatch,
}))
const rewriteTargetNames = new Set([...Object.values(targets), ...targetPatterns.map(({ name }) => name)])

const NODE_MODULES = '/node_modules/'

/**
 * @typedef {object} RewriteTarget
 * @property {string} moduleName
 * @property {string} filePath
 * @property {string} [activationName]
 * @property {string} [sourceMatch]
 */

/**
 * @param {string} filename
 * @returns {RewriteTarget|undefined}
 */
function getRewriteTarget (filename) {
  const nodeModulesIndex = filename.lastIndexOf(NODE_MODULES)
  if (nodeModulesIndex === -1) return

  const modulePath = filename.slice(nodeModulesIndex + NODE_MODULES.length)
  let moduleName = targets[modulePath]
  let sourceMatch
  if (!moduleName) {
    for (const { name, pattern, sourceMatch: expectedSource } of targetPatterns) {
      if (!modulePath.startsWith(`${name}/`) || !pattern.test(modulePath.slice(name.length + 1))) continue
      moduleName = name
      sourceMatch = expectedSource
      break
    }
  }
  if (typeof moduleName !== 'string') return
  const activationName = getRewriteActivationName(moduleName)

  const rewriteTarget = {
    moduleName,
    filePath: modulePath.slice(moduleName.length + 1),
  }
  if (activationName) rewriteTarget.activationName = activationName
  if (sourceMatch) rewriteTarget.sourceMatch = sourceMatch
  return rewriteTarget
}

function getRewriteTargetNames () {
  return rewriteTargetNames.values()
}

/**
 * @param {string} name
 */
function isRewriteTargetName (name) {
  return rewriteTargetNames.has(name)
}

/**
 * @param {string} moduleName
 */
function getRewriteActivationName (moduleName) {
  // Keep target-name-only consumers from loading every instrumentation descriptor.
  return require('./instrumentation-registry').getRewriteActivationName(moduleName)
}

module.exports = { getRewriteActivationName, getRewriteTarget, getRewriteTargetNames, isRewriteTargetName }
