name: Get Datadog credentials
description: Exchange GitHub OIDC token for Datadog API credentials via dd-sts.

outputs:
  api_key:
    description: "Datadog API key"
    value: ${{ steps.dd-sts.outputs.api_key }}
  app_key:
    description: "Datadog application key"
    value: ${{ steps.dd-sts.outputs.app_key }}

runs:
  using: composite
  steps:
    - name: Get Datadog credentials
      id: dd-sts
      uses: DataDog/dd-sts-action@2e8187910199bd93129520183c093e19aa585c75 # v1.0.0
      with:
        policy: dd-trace-js
