name: GitHub API Rate Limit Status
description: Output current GitHub API rate limit usage to the workflow log.
runs:
  using: composite
  steps:
    - name: Check GitHub API rate limit
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        response=$(curl -sS -H "Authorization: Bearer $GITHUB_TOKEN" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/rate_limit)

        limit=$(echo "$response" | jq '.rate.limit')
        used=$(echo "$response" | jq '.rate.used')
        remaining=$(echo "$response" | jq '.rate.remaining')
        reset_ts=$(echo "$response" | jq '.rate.reset')
        reset_human=$(date -u -d "@$reset_ts" '+%Y-%m-%d %H:%M:%S UTC' 2>/dev/null \
          || date -u -r "$reset_ts" '+%Y-%m-%d %H:%M:%S UTC')

        echo "::group::GitHub API Rate Limit Status"
        echo "Limit:     $limit"
        echo "Used:      $used"
        echo "Remaining: $remaining"
        echo "Reset:     $reset_human"
        echo "::endgroup::"
