'use strict'

const { mkdirSync, writeFileSync } = require('node:fs')
const { dirname } = require('node:path')

const { test, expect } = require('@playwright/test')

test('compares a text snapshot', () => {
  // Separate worker processes must not reuse a baseline generated by another test run.
  const name = `baseline-${process.pid}.txt`
  if (process.env.PLAYWRIGHT_SNAPSHOT_CASE === 'mismatch') {
    const path = test.info().snapshotPath(name)
    mkdirSync(dirname(path), { recursive: true })
    writeFileSync(path, 'expected content')
  }
  expect('actual content').toMatchSnapshot(name)
})
