// AUTO-GENERATED by dd-compile from mysql.analysis.json
// To customize tag extraction, edit this file directly.
// Re-running dd-compile will show a diff but won't overwrite without confirmation.

'use strict'

function connectionQueryClient (ctx) {
  return {
    operation: 'query',
    resource: ctx.arguments?.[0],
    meta: {
      'component': 'mysql',
      'span.kind': 'client',
      'db.type': 'mysql',
      'db.name': ctx.self?.config.database,
      'db.user': ctx.self?.config.user,
      'db.statement': ctx.arguments?.[0]
    },
    metrics: {
      'db.pid': ctx.self?.threadId
    }
  }
}

function poolQueryClient (ctx) {
  const config = ctx.self?.config?.connectionConfig

  const pool = ctx.self
  let threadId = pool?.threadId

  if (!threadId && pool) {
    const connArrays = [
      pool._allConnections,
      pool._freeConnections,
      pool._acquiringConnections,
      pool._connectionQueue
    ]

    for (const arr of connArrays) {
      if (arr && arr.length > 0) {
        for (const conn of arr) {
          if (conn?.threadId) {
            threadId = conn.threadId
            break
          }
        }
        if (threadId) break
      }
    }
  }

  const tags = {
    'component': 'mysql',
    'span.kind': 'client',
    'db.type': 'mysql',
    'db.name': config?.database,
    'db.user': config?.user,
    'db.statement': ctx.arguments?.[0]
  }

  return {
    operation: 'query',
    resource: ctx.arguments?.[0],
    meta: tags,
    metrics: {
      'db.pid': threadId
    }
  }
}

function connectionBegintransactionClient (ctx) {
  return {
    operation: 'beginTransaction',
    resource: ctx.arguments?.[0],
    meta: {
      'component': 'mysql',
      'span.kind': 'client',
      'db.type': 'mysql',
      'db.name': ctx.self?.config.database,
      'db.user': ctx.self?.config.user,
      'db.statement': ctx.arguments?.[0]
    },
    metrics: {
      'db.pid': ctx.self?.threadId
    }
  }
}

function connectionCommitClient (ctx) {
  return {
    operation: 'commit',
    resource: ctx.arguments?.[0],
    meta: {
      'component': 'mysql',
      'span.kind': 'client',
      'db.type': 'mysql',
      'db.name': ctx.self?.config?.database,
      'db.user': ctx.self?.config?.user,
    },
    metrics: {
      'db.pid': ctx.self?.threadId
    }
  }
}

function connectionRollbackClient (ctx) {
  return {
    operation: 'rollback',
    resource: ctx.arguments?.[0],
    meta: {
      'component': 'mysql',
      'span.kind': 'client',
      'db.type': 'mysql',
      'db.name': ctx.self?.config?.database,
      'db.user': ctx.self?.config?.user,
    },
    metrics: {
      'db.pid': ctx.self?.threadId
    }
  }
}

module.exports = {
  'tracing:apm:mysql:connection:query': connectionQueryClient,
  'tracing:apm:mysql:pool:query': poolQueryClient,
  'tracing:apm:mysql:connection:beginTransaction': connectionBegintransactionClient,
  'tracing:apm:mysql:connection:commit': connectionCommitClient,
  'tracing:apm:mysql:connection:rollback': connectionRollbackClient
}
