// AUTO-GENERATED by dd-compile from mysql.analysis.json
// To customize tag extraction, edit this file directly.
// Re-running dd-compile will show a diff but won't overwrite without confirmation.

'use strict'

function connectionQueryClient (ctx) {
  const config = ctx.self?.config
  const statement = typeof ctx.args[0] === 'string' ? ctx.args[0] : 'query'

  return {
    operation: 'query',
    resource: statement,
    meta: {
      'component': 'mysql',
      'span.kind': 'client',
      'db.type': 'mysql',
      'db.name': config?.database,
      'db.user': config?.user,
      'db.statement': statement
    },
    metrics: {
      'db.pid': ctx.self?.threadId
    }
  }
}

function poolQueryClient (ctx) {
  const config = ctx.self?.config?.connectionConfig
  const statement = typeof ctx.args[0] === 'string' ? ctx.args[0] : 'query'
  const pool = ctx.self
  let threadId = pool?.threadId

  if (!threadId && pool) {
    const connArrays = [
      pool._allConnections,
      pool._freeConnections,
      pool._acquiringConnections,
      pool._connectionQueue
    ]

    for (const arr of connArrays) {
      if (arr && arr.length > 0) {
        for (const conn of arr) {
          if (conn?.threadId) {
            threadId = conn.threadId
            break
          }
        }
        if (threadId) break
      }
    }
  }

  const meta = {
    'component': 'mysql',
    'span.kind': 'client',
    'db.type': 'mysql',
    'db.name': config?.database,
    'db.user': config?.user,
    'db.statement': statement
  }

  const metrics = {}
  if (threadId != null) {
    metrics['db.pid'] = threadId
  }

  return {
    operation: 'query',
    resource: statement,
    meta,
    metrics
  }
}

function connectionBegintransactionClient (ctx) {
  const config = ctx.self?.config

  return {
    operation: 'beginTransaction',
    resource: 'BEGIN TRANSACTION',
    meta: {
      'component': 'mysql',
      'span.kind': 'client',
      'db.type': 'mysql',
      'db.name': config?.database,
      'db.user': config?.user
    },
    metrics: {
      'db.pid': ctx.self?.threadId
    }
  }
}

function connectionCommitClient (ctx) {
  const config = ctx.self?.config

  return {
    operation: 'commit',
    resource: 'COMMIT',
    meta: {
      'component': 'mysql',
      'span.kind': 'client',
      'db.type': 'mysql',
      'db.name': config?.database,
      'db.user': config?.user
    },
    metrics: {
      'db.pid': ctx.self?.threadId
    }
  }
}

function connectionRollbackClient (ctx) {
  const config = ctx.self?.config

  return {
    operation: 'rollback',
    resource: 'ROLLBACK',
    meta: {
      'component': 'mysql',
      'span.kind': 'client',
      'db.type': 'mysql',
      'db.name': config?.database,
      'db.user': config?.user
    },
    metrics: {
      'db.pid': ctx.self?.threadId
    }
  }
}

module.exports = {
  'tracing:apm:mysql:connection:query': connectionQueryClient,
  'tracing:apm:mysql:pool:query': poolQueryClient,
  'tracing:apm:mysql:connection:begintransaction': connectionBegintransactionClient,
  'tracing:apm:mysql:connection:commit': connectionCommitClient,
  'tracing:apm:mysql:connection:rollback': connectionRollbackClient
}
