// AUTO-GENERATED by dd-compile from mysql.analysis.json
// To customize plugin behavior, edit this file directly.
// Re-running dd-compile will show a diff but won't overwrite without confirmation.

'use strict'

const DatabasePlugin = require('../../dd-trace/src/plugins/database')
const Extractors = require('./extractors')

class MysqlClientPlugin extends DatabasePlugin {
  static get id () {
    return 'mysql'
  }

  constructor (...args) {
    super(...args)
    this.subscribe()
  }

  subscribe () {
    this.registerOperation('tracing:apm:mysql:connection:query')
    this.registerOperation('tracing:apm:mysql:pool:query')
    this.registerOperation('tracing:apm:mysql:connection:begintransaction')
    this.registerOperation('tracing:apm:mysql:connection:commit')
    this.registerOperation('tracing:apm:mysql:connection:rollback')
  }

  bindStart (ctx, channel) {
    const options = Extractors[channel]?.(ctx)
    if (!options) return ctx.currentStore

    this.startSpan(`${this.constructor.id}.${options.operation}`, options, ctx)
    return ctx.currentStore
  }

  error (ctx) {
    const span = ctx?.currentStore?.span
    if (span && ctx.error) {
      this.addError(ctx.error, span)
    }
  }

  asyncEnd (ctx) {
    const span = ctx?.currentStore?.span
    if (span) {
      span.finish()
    }
  }
}

module.exports = MysqlClientPlugin
