// AUTO-GENERATED by dd-compile from mysql.analysis.json
// To customize plugin behavior, edit this file directly.
// Re-running dd-compile will show a diff but won't overwrite without confirmation.

'use strict'

const DatabasePlugin = require('../../dd-trace/src/plugins/database')
const Extractors = require('./extractors')

class MysqlClientPlugin extends DatabasePlugin {
  static get id () {
    return 'mysql'
  }

  constructor (...args) {
    super(...args)
    this.subscribe()
  }

  subscribe () {
    this.registerOperation('tracing:apm:mysql:connection:query')
    this.registerOperation('tracing:apm:mysql:pool:query')
    this.registerOperation('tracing:apm:mysql:connection:beginTransaction')
    this.registerOperation('tracing:apm:mysql:connection:commit')
    this.registerOperation('tracing:apm:mysql:connection:rollback')
  }

  bindStart (ctx, channel) {
    const options = Extractors[channel]?.(ctx)
    this.startSpan(`${this.constructor.id}.${options.operation}`, options, ctx)

    return ctx.currentStore
  }

  asyncEnd (ctx) {
    this.finish(ctx)
  }

  finish (ctx) {
    if (!ctx.result) return

    const span = ctx.currentStore?.span
    if (span) {
      super.finish(ctx)
    }
  }
}

module.exports = MysqlClientPlugin
