// AUTO-GENERATED by dd-compile from log4js.analysis.json
// To customize tag extraction, edit this file directly.
// Re-running dd-compile will show a diff but won't overwrite without confirmation.

'use strict'

module.exports = {}
