name: Install dependencies
description: Install dependencies
runs:
  using: composite
  steps:
    - id: install-cache
      uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
      with:
        key: install-cache-${{ github.workflow }}-${{ github.job }}-${{ hashFiles('bun.lock') }}-v2
        path: node_modules.tar
      if: inputs.cache == 'true'
    - run: tar -xf node_modules.tar
      shell: bash
      if: inputs.cache == 'true' && steps.install-cache.outputs.cache-hit == 'true'
      # Retry in case of server error from registry.
      # Wait 60 seconds to give the registry server time to heal.
    - run: bun install --linker=hoisted --trust || sleep 60 && bun install --linker=hoisted --trust
      shell: bash
      env:
        _DD_IGNORE_ENGINES: 'true'
    - run: tar -cf node_modules.tar node_modules
      shell: bash
      if: inputs.cache == 'true' && steps.install-cache.outputs.cache-hit != 'true'
