name: Install dependencies
description: Install dependencies
inputs:
  cache:
    description: "Whether to enable caching of node_modules."
    required: false
    default: 'false'
runs:
  using: composite
  steps:
    - id: yarn-cache
      uses: actions/cache@v4
      with:
        key: yarn-cache-${{ github.workflow }}-${{ github.job }}-${{ hashFiles('yarn.lock') }}
        path: node_modules.tar
      if: inputs.cache == 'true'
    - run: tar -xf node_modules.tar
      shell: bash
      if: inputs.cache == 'true' && steps.yarn-cache.outputs.cache-hit == 'true'
      # Retry in case of server error from registry.
    - run: yarn install --frozen-lockfile --ignore-engines || yarn install --frozen-lockfile --ignore-engines
      shell: bash
    - run: 7z -mx0 -snl a node_modules.tar node_modules
      shell: bash
      if: inputs.cache == 'true' && steps.yarn-cache.outputs.cache-hit != 'true'
