name: Install dependencies
description: Install dependencies
runs:
  using: composite
  steps:
    - uses: nick-fields/retry@ad984534de44a9489a53aefd81eb77f87c70dc60 # v4.0.0
      env:
        _DD_IGNORE_ENGINES: 'true'
      with:
        max_attempts: 3
        timeout_minutes: 5
        retry_wait_seconds: 30
        command: bun install --linker=hoisted --trust --network-concurrency 8
