name: Install dependencies
runs:
  using: composite
  steps: # retry in case of server error from registry
    - run: yarn install --ignore-engines || yarn install --ignore-engines
      shell: bash

