name: Install dependencies
description: Install dependencies
runs:
  using: composite
  steps: # retry in case of server error from registry
    - run: yarn install --frozen-lockfile --ignore-engines || yarn install --frozen-lockfile --ignore-engines
      shell: bash

