name: "Start the APM Test Agent"
description: "Starts the APM Test Agent image with environment."
runs:
  using: composite
  steps:
    - uses: ./.github/actions/checkout
    - run: docker compose up -d testagent || docker compose up -d testagent
      shell: bash
