name: "Start the APM Test Agent"
description: "Starts the APM Test Agent image with environment."
runs:
  using: composite
  steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - run: docker compose up -d testagent || docker compose up -d testagent
      shell: bash
