name: "Start the APM Test Agent"
description: "Starts the APM Test Agent image with environment."
runs:
  using: composite
  steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
    - run: docker compose up -d testagent || docker compose up -d testagent
      shell: bash
