name: "Start the APM Test Agent"
description: "Starts the APM Test Agent image with environment."
runs:
  using: composite
  steps:
    - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
    - run: docker compose up -d testagent || docker compose up -d testagent
      shell: bash
