/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class Rewriter {
  constructor()
  rewrite(code: string, file: string, sourceMap?: string | undefined | null): string
}
