'use strict'

module.exports = {
  'amqp10': require('./amqp10'),
  'amqplib': require('./amqplib'),
  'bluebird': require('./bluebird'),
  'bunyan': require('./bunyan'),
  'cassandra-driver': require('./cassandra-driver'),
  'dns': require('./dns'),
  'elasticsearch': require('./elasticsearch'),
  'express': require('./express'),
  'generic-pool': require('./generic-pool'),
  'graphql': require('./graphql'),
  'hapi': require('./hapi'),
  'http': require('./http'),
  'ioredis': require('./ioredis'),
  'koa': require('./koa'),
  'memcached': require('./memcached'),
  'mongodb-core': require('./mongodb-core'),
  'mysql': require('./mysql'),
  'mysql2': require('./mysql2'),
  'net': require('./net'),
  'pg': require('./pg'),
  'pino': require('./pino'),
  'q': require('./q'),
  'redis': require('./redis'),
  'restify': require('./restify'),
  'when': require('./when'),
  'winston': require('./winston')
}
