name: Get Datadog App key
description: Exchange GitHub OIDC token for a Datadog App key via dd-sts.

outputs:
  app_key:
    description: "Datadog application key"
    value: ${{ steps.dd-sts.outputs.app_key }}

runs:
  using: composite
  steps:
    - name: Get Datadog App key
      id: dd-sts
      uses: DataDog/dd-sts-action@7d2d231c02fd54a3da912e582ff87cb995d1fd30 # v1.0.4
      with:
        policy: dd-trace-js
