name: Get Datadog App key
description: Exchange GitHub OIDC token for a Datadog App key via dd-sts.

outputs:
  app_key:
    description: "Datadog application key"
    value: ${{ steps.dd-sts.outputs.app_key }}

runs:
  using: composite
  steps:
    - name: Get Datadog App key
      id: dd-sts
      uses: DataDog/dd-sts-action@2e8187910199bd93129520183c093e19aa585c75 # v1.0.0
      with:
        policy: dd-trace-js
