'use strict'

const dc = require('dc-polyfill')

const { storage } = require('../../../datadog-core')

const legacyStorage = storage('legacy')

/**
 * Resolve the package-scoped source channel generated by an Orchestrion
 * transform. Shared domain behavior belongs on a downstream semantic channel.
 *
 * @param {string} moduleName Instrumented package or platform module name.
 * @param {string} targetName Orchestrion transform channel name.
 * @returns {import('diagnostics_channel').TracingChannel} Transform lifecycle channel.
 */
function getOrchestrionChannel (moduleName, targetName) {
  return dc.tracingChannel(`orchestrion:${moduleName}:${targetName}`)
}

/**
 * Enter a semantic start channel from an Orchestrion start binding.
 *
 * The normalizer should enrich and return the transform context instead of
 * allocating a second envelope on hot paths that do not require one. Prefer
 * `SemanticLifecycleBridge` when the source also needs contributor composition
 * and exactly-once semantic error/finish handling.
 *
 * @param {object} context Orchestrion transform context.
 * @param {import('diagnostics_channel').Channel} semanticStart Semantic start channel.
 * @param {(context: object) => object} normalize Source adapter normalizer.
 * @returns {object|undefined} Store to bind around the transformed function call.
 */
function runSemanticStart (context, semanticStart, normalize) {
  return semanticStart.runStores(normalize(context), getStore)
}

function getStore () {
  return legacyStorage.getStore()
}

module.exports = { getOrchestrionChannel, runSemanticStart }
