issuer: https://token.actions.githubusercontent.com

subject: repo:DataDog/dd-trace-js:ref:refs/heads/master

claim_pattern:
  event_name: workflow_dispatch
  ref: refs/heads/master
  job_workflow_ref: DataDog/dd-trace-js/\.github/workflows/custom-node-version-dispatch\.yml@refs/heads/master

permissions:
  actions: write
