issuer: https://token.actions.githubusercontent.com

subject: repo:DataDog/dd-trace-js:ref:refs/heads/main

claim_pattern:
  event_name: (workflow_dispatch|schedule)
  ref: refs/heads/main
  ref_protected: "true"
  job_workflow_ref: DataDog/dd-trace-js/.github/workflows/release-proposal.yml@refs/heads/main

permissions:
  contents: write
  pull_requests: write
  workflows: write
