name: Push to Test Optimization
description: Upload JUnit XML test results to Datadog Test Optimization
inputs:
  dd_api_key:
    description: DD_API_KEY used to push test results
    required: true
runs:
  using: composite
  steps:
    - if: github.actor != 'dependabot[bot]'
      # see https://docs.github.com/en/actions/reference/workflows-and-actions/events-that-trigger-workflows#pull-request-events-for-forked-repositories
      #
      # > Workflows triggered by Dependabot pull requests are treated as though they are
      # >  from a forked repository, and are also subject to these restrictions.
      #
      # Which means they do not have access to secrets.
      uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
      with:
        path: ${{ github.action_path }}/node_modules
        key: push-to-test-optimization-${{ hashFiles('.github/actions/push_to_test_optimization/package.json') }}
    - if: github.actor != 'dependabot[bot]'
      uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
      with:
        node-version: '20'
    - if: github.actor != 'dependabot[bot]'
      shell: bash
      run: |
        yarn install --no-lockfile
        echo "$(pwd)/node_modules/.bin" >> $GITHUB_PATH
      working-directory: ${{ github.action_path }}
    - if: github.actor != 'dependabot[bot]'
      shell: bash
      run: datadog-ci junit upload --service dd-trace-js-tests .
      env:
        DD_API_KEY: ${{ inputs.dd_api_key }}
