name: AI Guard

on:
  pull_request:
  push:
    branches: [master, mq-working-branch-master-*]
  schedule:
    - cron: 0 4 * * *

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

env:
  MOCHA_OPTIONS: ${{ github.ref == 'refs/heads/master' && '--retries 1' || '' }}

jobs:
  macos:
    name: ${{ github.workflow }} / macos
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/node/latest
      - uses: ./.github/actions/install
      - run: yarn test:aiguard:ci
      - uses: ./.github/actions/coverage
        with:
          flags: aiguard-macos
      - uses: ./.github/actions/push_to_test_optimization
        if: "!cancelled()"
        with:
          dd_api_key: ${{ secrets.DD_API_KEY }}

  ubuntu:
    name: ${{ github.workflow }} / ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/node/oldest-maintenance-lts
      - uses: ./.github/actions/install
      - run: yarn test:aiguard:ci
      - uses: ./.github/actions/node/newest-maintenance-lts
      - run: yarn test:aiguard:ci
      - uses: ./.github/actions/node/active-lts
      - run: yarn test:aiguard:ci
      - uses: ./.github/actions/node/latest
      - run: yarn test:aiguard:ci
      - uses: ./.github/actions/coverage
        with:
          flags: aiguard-ubuntu
      - uses: ./.github/actions/push_to_test_optimization
        if: "!cancelled()"
        with:
          dd_api_key: ${{ secrets.DD_API_KEY }}

  windows:
    name: ${{ github.workflow }} / windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/node/latest
      - uses: ./.github/actions/install
        with:
          cache: "true"
      - run: yarn test:aiguard:ci
      - uses: ./.github/actions/coverage
        with:
          flags: aiguard-windows
      - uses: ./.github/actions/push_to_test_optimization
        if: "!cancelled()"
        with:
          dd_api_key: ${{ secrets.DD_API_KEY }}

  integration:
    name: ${{ github.workflow }} / integration (node-${{ matrix.version }})
    strategy:
      matrix:
        version: [maintenance, active, latest]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/node
        with:
          version: ${{ matrix.version }}
      - uses: ./.github/actions/install
      - run: yarn test:integration:aiguard
      - uses: ./.github/actions/push_to_test_optimization
        if: "!cancelled()"
        with:
          dd_api_key: ${{ secrets.DD_API_KEY }}
