name: All Green
on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: 0 4 * * *

concurrency:
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/master' && github.run_id || github.ref }}
  cancel-in-progress: true

jobs:
  all-green:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          sparse-checkout-cone-mode: false
          sparse-checkout: |
            .github
            scripts
      - uses: ./.github/actions/node
        with:
          version: active
      - run: yarn add @actions/core @actions/github octokit
      - run: node scripts/all-green.mjs
        env:
          DELAY: ${{ github.run_attempt == 1 && '5' || '0' }} # 5 minutes on first attempt, no delay on reruns
          GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}
          GITHUB_TOKEN: ${{ github.token }}
          POLLING_INTERVAL: 1
          RETRIES: 30
