name: APM Capabilities

on:
  pull_request:
  push:
    branches: [master, mq-working-branch-master-*]
  schedule:
    - cron: 0 4 * * *
  workflow_dispatch:
    inputs:
      latest-version:
        description: "Node version to use"
        required: false
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ inputs.latest-version }}-${{ github.ref || github.run_id }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

env:
  MOCHA_OPTIONS: ${{ github.ref == 'refs/heads/master' && '--retries 1' || '' }}
  LATEST_VERSION: ${{ inputs.latest-version }}

jobs:
  tracing-macos:
    runs-on: macos-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/dd-sts-api-key
        id: dd-sts
      - uses: ./.github/actions/node/latest
      - uses: ./.github/actions/install
      - run: yarn test:trace:core:ci
      - uses: ./.github/actions/coverage
        with:
          flags: apm-capabilities-tracing-macos
          dd_api_key: ${{ steps.dd-sts.outputs.api_key }}
      - uses: ./.github/actions/push_to_test_optimization
        if: "!cancelled()"
        with:
          dd_api_key: ${{ steps.dd-sts.outputs.api_key }}

  tracing-ubuntu:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/dd-sts-api-key
        id: dd-sts
      - uses: ./.github/actions/node/oldest-maintenance-lts
      - uses: ./.github/actions/install
      - run: yarn test:trace:core:ci
      - uses: ./.github/actions/node/newest-maintenance-lts
      - run: yarn test:trace:core:ci
      - uses: ./.github/actions/node/active-lts
      - run: yarn test:trace:core:ci
      - uses: ./.github/actions/node/latest
      - run: yarn test:trace:core:ci
      - uses: ./.github/actions/coverage
        with:
          flags: apm-capabilities-tracing-ubuntu
          dd_api_key: ${{ steps.dd-sts.outputs.api_key }}
      - uses: ./.github/actions/push_to_test_optimization
        if: "!cancelled()"
        with:
          dd_api_key: ${{ steps.dd-sts.outputs.api_key }}

  tracing-windows:
    runs-on: windows-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/dd-sts-api-key
        id: dd-sts
      - uses: ./.github/actions/node/latest
      - uses: ./.github/actions/install
        with:
          cache: "true"
      - run: yarn test:trace:core:ci
      - uses: ./.github/actions/coverage
        with:
          flags: apm-capabilities-tracing-windows
          dd_api_key: ${{ steps.dd-sts.outputs.api_key }}
      - uses: ./.github/actions/push_to_test_optimization
        if: "!cancelled()"
        with:
          dd_api_key: ${{ steps.dd-sts.outputs.api_key }}
