name: APM Capabilities

on:
  pull_request:
  push:
    branches: [master]
  schedule:
    - cron: 0 4 * * *
  workflow_dispatch:
    inputs:
      nightly-version:
        description: 'Nightly node version to use'
        required: false
        default: 'false'
        type: string


concurrency:
  group: ${{ inputs.nightly-version && format('{0}-{1}', github.workflow, inputs.nightly-version) || github.workflow }}-${{ github.ref || github.run_id }}"
  cancel-in-progress: true

env:
  MOCHA_OPTIONS: ${{ github.ref == 'refs/heads/master' && '--retries 1' || '' }}
  NIGHTLY_VERSION: ${{ inputs.nightly-version && format('{0}-{1}', inputs.nightly-version, 'nightly')

jobs:
  tracing-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: ./.github/actions/node/latest
      - uses: ./.github/actions/install
      - run: yarn test:trace:core:ci
      - uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7 # v5.5.1
      - uses: DataDog/junit-upload-github-action@762867566348d59ac9bcf479ebb4ec040db8940a  # v2.0.0
        if: always()
        with:
          api_key: ${{ secrets.DD_API_KEY }}
          service: dd-trace-js-tests

  tracing-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: ./.github/actions/node/oldest-maintenance-lts
      - uses: ./.github/actions/install
      - run: yarn test:trace:core:ci
      - uses: ./.github/actions/node/newest-maintenance-lts
      - run: yarn test:trace:core:ci
      - uses: ./.github/actions/node/active-lts
      - run: yarn test:trace:core:ci
      - uses: ./.github/actions/node/latest
      - run: yarn test:trace:core:ci
      - uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7 # v5.5.1
      - uses: DataDog/junit-upload-github-action@762867566348d59ac9bcf479ebb4ec040db8940a  # v2.0.0
        if: always()
        with:
          api_key: ${{ secrets.DD_API_KEY }}
          service: dd-trace-js-tests

  tracing-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: ./.github/actions/node/latest
      - uses: ./.github/actions/install
        with:
          cache: 'true'
      - run: yarn test:trace:core:ci
      - uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7 # v5.5.1
      - uses: DataDog/junit-upload-github-action@762867566348d59ac9bcf479ebb4ec040db8940a  # v2.0.0
        if: always()
        with:
          api_key: ${{ secrets.DD_API_KEY }}
          service: dd-trace-js-tests
