name: APM Capabilities

on:
  pull_request:
  push:
    branches: [master]
  schedule:
    - cron: 0 4 * * *
  workflow_call:
    inputs:
      runNightly:
        description: 'Whether to run nightly tests'
        required: false
        default: 'false'
        type: string
      workflowName:
        description: 'Workflow Name accessible from inputs'
        required: false
        default: 'NightlyCall'
        type: string

concurrency:
  group: ${{ inputs.runNightly == 'true' && inputs.workflowName || github.workflow }}-${{ github.ref || github.run_id }}"
  cancel-in-progress: ${{ inputs.runNightly != 'true' }}

env:
  MOCHA_OPTIONS: ${{ github.ref == 'refs/heads/master' && '--retries 1' || '' }}

jobs:
  debug-concurrency:
    runs-on: ubuntu-latest
    steps:
      - name: Echo concurrency group values
        run: |
          echo "=== APM Integrations Workflow Context ==="
          echo "github.workflow: ${{ github.workflow }}"
          echo "github.job: ${{ github.job }}"
          echo "github.ref: ${{ github.ref }}"
          echo "github.ref: ${{ github.workflow_ref }}"
          echo "github.run_id: ${{ github.run_id }}"
          echo "inputs.runNightly: ${{ inputs.runNightly }}"
          echo "---"
          echo "Current concurrency group: ${{ github.workflow }}-${{ inputs.runNightly == 'true' && github.run_id || github.ref || github.run_id }}"
          echo "cancel-in-progress: ${{ inputs.runNightly != 'true' }}"
          echo "This is the global var $GLOBAL_VAR"
  tracing-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: ./.github/actions/node/latest
      - uses: ./.github/actions/install
      - run: yarn test:trace:core:ci
      - uses: ./.github/actions/node/nightly
        if: inputs.runNightly == 'true'
      - run: yarn test:trace:core:ci
      - uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7 # v5.5.1

  tracing-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: ./.github/actions/node/oldest-maintenance-lts
      - uses: ./.github/actions/install
      - run: yarn test:trace:core:ci
      - uses: ./.github/actions/node/newest-maintenance-lts
      - run: yarn test:trace:core:ci
      - uses: ./.github/actions/node/active-lts
      - run: yarn test:trace:core:ci
      - uses: ./.github/actions/node/latest
      - run: yarn test:trace:core:ci
      - uses: ./.github/actions/node/nightly
        if: inputs.runNightly == 'true'
      - run: yarn test:trace:core:ci
        if: inputs.runNightly == 'true'
      - uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7 # v5.5.1

  tracing-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: ./.github/actions/node/latest
      - uses: ./.github/actions/install
        with:
          cache: 'true'
      - run: yarn test:trace:core:ci
      - uses: ./.github/actions/node/nightly
        if: inputs.runNightly == 'true'
      - run: yarn test:trace:core:ci
        if: inputs.runNightly == 'true'
      - uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7 # v5.5.1
