name: CI Visibility performance and correctness tests

on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: 0 4 * * *
    - cron: 20 4 * * *
    - cron: 40 4 * * *

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  ci-visibility-tests:
    name: CI Visibility performance and correctness tests
    runs-on: ubuntu-latest
    env:
      ROBOT_CI_GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.ROBOT_CI_GITHUB_PERSONAL_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ./.github/actions/node/18
      - name: CI Visibility Performance Overhead Test
        run: yarn bench:e2e:ci-visibility
