name: Debugger

on:
  pull_request:
  push:
    branches: [master, mq-working-branch-master-*]
  schedule:
    - cron: 0 4 * * *

concurrency:
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/master' && github.run_id || github.ref }}
  cancel-in-progress: true

jobs:
  ubuntu:
    name: ${{ github.workflow }} / ubuntu (node-${{ matrix.version }})
    strategy:
      fail-fast: false
      matrix:
        version: [oldest, maintenance, active, latest]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: ./.github/actions/node
        with:
          version: ${{ matrix.version }}
      - uses: ./.github/actions/install
      - run: yarn test:code-origin:ci
      - run: yarn test:debugger:ci
      - run: yarn test:integration:debugger:coverage
      - uses: ./.github/actions/coverage
        with:
          flags: debugger-ubuntu-${{ matrix.version }}
      - uses: ./.github/actions/upload-junit-artifacts
        if: "!cancelled()"
        with:
          id: ${{ github.job }}-${{ strategy.job-index }}
