name: ESLint Rules

on:
  pull_request:
    paths:
      - "eslint-rules/**"
  push:
    branches: [master, mq-working-branch-master-*]
    paths:
      - "eslint-rules/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/master' && github.run_id || github.ref }}
  cancel-in-progress: true

jobs:
  eslint-rules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: ./.github/actions/node/latest
      - uses: ./.github/actions/install
      - run: npm run test:eslint-rules
