name: ESLint Rules

on:
  pull_request:
    paths:
      - "eslint-rules/**"
  push:
    branches: [master, mq-working-branch-master-*]
    paths:
      - "eslint-rules/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/master' && github.run_id || github.ref }}
  cancel-in-progress: true

jobs:
  eslint-rules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./.github/actions/node/latest
      - uses: ./.github/actions/install
      - run: npm run test:eslint-rules
