name: '[Flakiness Report]'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1'

jobs:
  flakiness:
    runs-on: ubuntu-latest
    permissions:
      actions: read
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DAYS: '7'
      OCCURRENCES: '2'
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          sparse-checkout-cone-mode: false
          sparse-checkout: |
            .github
            scripts
      - uses: ./.github/actions/node
        with:
          version: ''
      - run: npm install octokit
      - run: node scripts/flakiness.mjs
      - run: cat flakiness.md >> $GITHUB_STEP_SUMMARY
      - id: slack
        run: echo "report=$(cat flakiness.txt)" >> $GITHUB_OUTPUT
      - uses: slackapi/slack-github-action@91efab103c0de0a537f72a35f6b8cda0ee76bf0a # v2.1.0
        if: github.event_name == 'schedule'
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: ${{ secrets.SLACK_CHANNEL_ID }}
            blocks:
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: "${{ steps.slack.outputs.report }}"
