name: Flakiness Report

on:
  schedule:
    - cron: '0 6 * * *'

jobs:
  flakiness:
    runs-on: ubuntu-latest
    permissions:
      actions: read
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ./.github/actions/node
        with:
          version: ''
      - run: node scripts/flakiness.mjs
