name: Flakiness Report

on:
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: '0 6 * * 1'

jobs:
  flakiness:
    strategy:
      matrix:
        branch: [master, all]
    runs-on: ubuntu-latest
    permissions:
      actions: read
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DAYS: '7'
      OCCURRENCES: '2'
      BRANCH: ${{ matrix.branch == 'all' && '' || matrix.branch }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          sparse-checkout-cone-mode: false
          sparse-checkout: |
            .github
            scripts
      - uses: ./.github/actions/node
        with:
          version: ''
      - run: npm install octokit
      - id: report
        run: |
          {
            echo 'markdown<<EOF'
            node scripts/flakiness.mjs
            echo EOF
          } >> $GITHUB_OUTPUT
      - run: echo "${{ steps.report.outputs.markdown }}" >> $GITHUB_STEP_SUMMARY
      - uses: slackapi/slack-github-action@91efab103c0de0a537f72a35f6b8cda0ee76bf0a # v2.1.0
        if: github.event_name == 'schedule' && matrix.branch == 'all'
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: ${{ secrets.SLACK_CHANNEL_ID }}
            text: ${{ steps.report.outputs.markdown }}
