name: LLMObs

on:
  pull_request:
  push:
    branches: [master, mq-working-branch-master-*]
  schedule:
    - cron: 0 4 * * *
  workflow_dispatch:
    inputs:
      latest-version:
        description: "Node version to use"
        required: false
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ inputs.latest-version }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

env:
  MOCHA_OPTIONS: ${{ github.ref == 'refs/heads/master' && '--retries 1' || '' }}
  LATEST_VERSION: ${{ inputs.latest-version }}

jobs:
  sdk:
    strategy:
      matrix:
        version: [oldest, maintenance, active, latest]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/dd-sts-api-key
        id: dd-sts
      - uses: ./.github/actions/testagent/start
      - uses: ./.github/actions/node
        with:
          version: ${{ matrix.version }}
      - uses: ./.github/actions/install
      - run: yarn test:llmobs:sdk:ci
      - if: always()
        uses: ./.github/actions/testagent/logs
        with:
          suffix: llmobs-${{ github.job }}-${{ matrix.version }}
      - uses: ./.github/actions/coverage
        with:
          flags: llmobs-sdk-${{ matrix.version }}
          dd_api_key: ${{ steps.dd-sts.outputs.api_key }}
      - uses: ./.github/actions/push_to_test_optimization
        if: "!cancelled()"
        with:
          dd_api_key: ${{ steps.dd-sts.outputs.api_key }}

  openai:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    env:
      PLUGINS: openai
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/dd-sts-api-key
        id: dd-sts
      - uses: ./.github/actions/testagent/start
      - uses: ./.github/actions/node/oldest-maintenance-lts
      - uses: ./.github/actions/install
      - run: yarn test:plugins:ci
      - run: yarn test:llmobs:plugins:ci
        shell: bash
      - uses: ./.github/actions/node/latest
      - run: yarn test:plugins:ci
      - run: yarn test:llmobs:plugins:ci
        shell: bash
      - uses: ./.github/actions/coverage
        with:
          flags: llmobs-${{ github.job }}
          dd_api_key: ${{ steps.dd-sts.outputs.api_key }}
      - if: always()
        uses: ./.github/actions/testagent/logs
        with:
          suffix: llmobs-${{ github.job }}
      - uses: ./.github/actions/push_to_test_optimization
        if: "!cancelled()"
        with:
          dd_api_key: ${{ steps.dd-sts.outputs.api_key }}

  langchain:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    env:
      PLUGINS: langchain
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/dd-sts-api-key
        id: dd-sts
      - uses: ./.github/actions/testagent/start
      - uses: ./.github/actions/node/oldest-maintenance-lts
      - uses: ./.github/actions/install
      - run: yarn test:plugins:ci
      - run: yarn test:llmobs:plugins:ci
        shell: bash
      - uses: ./.github/actions/node/latest
      - run: yarn test:plugins:ci
      - run: yarn test:llmobs:plugins:ci
        shell: bash
      - uses: ./.github/actions/coverage
        with:
          flags: llmobs-${{ github.job }}
          dd_api_key: ${{ steps.dd-sts.outputs.api_key }}
      - if: always()
        uses: ./.github/actions/testagent/logs
        with:
          suffix: llmobs-${{ github.job }}
      - uses: ./.github/actions/push_to_test_optimization
        if: "!cancelled()"
        with:
          dd_api_key: ${{ steps.dd-sts.outputs.api_key }}

  bedrock:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    env:
      PLUGINS: aws-sdk
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/dd-sts-api-key
        id: dd-sts
      - uses: ./.github/actions/testagent/start
      - uses: ./.github/actions/node/oldest-maintenance-lts
      - uses: ./.github/actions/install
      - run: yarn test:llmobs:plugins:ci
        shell: bash
      - uses: ./.github/actions/node/latest
      - run: yarn test:llmobs:plugins:ci
        shell: bash
      - uses: ./.github/actions/coverage
        with:
          flags: llmobs-${{ github.job }}
          dd_api_key: ${{ steps.dd-sts.outputs.api_key }}
      - if: always()
        uses: ./.github/actions/testagent/logs
        with:
          suffix: llmobs-${{ github.job }}
      - uses: ./.github/actions/push_to_test_optimization
        if: "!cancelled()"
        with:
          dd_api_key: ${{ steps.dd-sts.outputs.api_key }}

  vertex-ai:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    env:
      PLUGINS: google-cloud-vertexai
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/dd-sts-api-key
        id: dd-sts
      - uses: ./.github/actions/testagent/start
      - uses: ./.github/actions/node/oldest-maintenance-lts
      - uses: ./.github/actions/install
      - run: yarn test:plugins:ci
      - run: yarn test:llmobs:plugins:ci
        shell: bash
      - uses: ./.github/actions/node/latest
      - run: yarn test:plugins:ci
      - run: yarn test:llmobs:plugins:ci
        shell: bash
      - uses: ./.github/actions/coverage
        with:
          flags: llmobs-${{ github.job }}
          dd_api_key: ${{ steps.dd-sts.outputs.api_key }}
      - if: always()
        uses: ./.github/actions/testagent/logs
        with:
          suffix: llmobs-${{ github.job }}
      - uses: ./.github/actions/push_to_test_optimization
        if: "!cancelled()"
        with:
          dd_api_key: ${{ steps.dd-sts.outputs.api_key }}

  ai:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    env:
      PLUGINS: ai
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/dd-sts-api-key
        id: dd-sts
      - uses: ./.github/actions/testagent/start
      - uses: ./.github/actions/node/oldest-maintenance-lts
      - uses: ./.github/actions/install
      - run: yarn test:plugins:ci
      - run: yarn test:llmobs:plugins:ci
        shell: bash
      - uses: ./.github/actions/node/latest
      - run: yarn test:plugins:ci
      - run: yarn test:llmobs:plugins:ci
        shell: bash
      - uses: ./.github/actions/coverage
        with:
          flags: llmobs-${{ github.job }}
          dd_api_key: ${{ steps.dd-sts.outputs.api_key }}
      - if: always()
        uses: ./.github/actions/testagent/logs
        with:
          suffix: llmobs-${{ github.job }}
      - uses: ./.github/actions/push_to_test_optimization
        if: "!cancelled()"
        with:
          dd_api_key: ${{ steps.dd-sts.outputs.api_key }}

  anthropic:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    env:
      PLUGINS: anthropic
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/dd-sts-api-key
        id: dd-sts
      - uses: ./.github/actions/testagent/start
      - uses: ./.github/actions/node/oldest-maintenance-lts
      - uses: ./.github/actions/install
      - run: yarn test:plugins:ci
      - run: yarn test:llmobs:plugins:ci
        shell: bash
      - uses: ./.github/actions/node/latest
      - run: yarn test:plugins:ci
      - run: yarn test:llmobs:plugins:ci
        shell: bash
      - uses: ./.github/actions/coverage
        with:
          flags: llmobs-${{ github.job }}
          dd_api_key: ${{ steps.dd-sts.outputs.api_key }}
      - if: always()
        uses: ./.github/actions/testagent/logs
        with:
          suffix: llmobs-${{ github.job }}
      - uses: ./.github/actions/push_to_test_optimization
        if: "!cancelled()"
        with:
          dd_api_key: ${{ steps.dd-sts.outputs.api_key }}

  google-genai:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    env:
      PLUGINS: google-genai
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/dd-sts-api-key
        id: dd-sts
      - uses: ./.github/actions/testagent/start
      - uses: ./.github/actions/node/oldest-maintenance-lts
      - uses: ./.github/actions/install
      - run: yarn test:plugins:ci
      - run: yarn test:llmobs:plugins:ci
        shell: bash
      - uses: ./.github/actions/node/latest
      - run: yarn test:plugins:ci
      - run: yarn test:llmobs:plugins:ci
        shell: bash
      - uses: ./.github/actions/coverage
        with:
          flags: llmobs-${{ github.job }}
          dd_api_key: ${{ steps.dd-sts.outputs.api_key }}
      - if: always()
        uses: ./.github/actions/testagent/logs
        with:
          suffix: llmobs-${{ github.job }}
      - uses: ./.github/actions/push_to_test_optimization
        if: "!cancelled()"
        with:
          dd_api_key: ${{ steps.dd-sts.outputs.api_key }}
  
  langgraph:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    env:
      PLUGINS: langgraph
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/plugins/test
