name: Nightly Testing

on:
  workflow_dispatch:

jobs:
  nightly:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/apm-integrations
        with:
          runNightly: 'true'
      - uses: ./.github/workflows/apm-capabilities
        with:
          runNightly: 'true'
      - uses: ./.github/workflows/llmobs
        with:
          runNightly: 'true'
      - uses: ./.github/workflows/platform
        with:
          runNightly: 'true'
      - uses: ./.github/workflows/serverless
        with:
          runNightly: 'true'
