name: Nightly Testing
env:
  GLOBAL_VAR: "This is a global variable"

on:
  workflow_dispatch:
    inputs:
      runApmIntegrations:
        description: 'APM Integration Tests'
        required: false
        default: true
        type: boolean
      runApmCapabilities:
        description: 'APM Capabilities Tests'
        required: false
        default: true
        type: boolean
      runLlmobs:
        description: 'LLM-OBS Tests'
        required: false
        default: true
        type: boolean
      runPlatform:
        description: 'Platform Tests'
        required: false
        default: true
        type: boolean
      runServerless:
        description: 'Serverless Tests'
        required: false
        default: true
        type: boolean

jobs:
  apm-integrations:
    if: inputs.runApmIntegrations
    uses: ./.github/workflows/apm-integrations.yml
    with:
      runNightly: ${{ 'true' }}
      workflowName: apm-integrations

  apm-capabilities:
    if: inputs.runApmCapabilities
    uses: ./.github/workflows/apm-capabilities.yml
    with:
      runNightly: ${{ 'true' }}
      workflowName: apm-capabilities

  llmobs:
    if: inputs.runLlmobs
    uses: ./.github/workflows/llmobs.yml
    with:
      runNightly: ${{ 'true' }}
      workflowName: llmobs

  platform:
    if: inputs.runPlatform
    uses: ./.github/workflows/platform.yml
    with:
      runNightly: ${{ 'true' }}
      workflowName: platform

  serverless:
    if: inputs.runServerless
    uses: ./.github/workflows/serverless.yml
    with:
      runNightly: ${{ 'true' }}
      workflowName: serverless
