name: Profiling

on:
  pull_request:
  push:
    branches: [master, mq-working-branch-master-*]
  schedule:
    - cron: 0 4 * * *
  workflow_dispatch:
    inputs:
      latest-version:
        description: "Node version to use"
        required: false
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ inputs.latest-version }}-${{ github.ref == 'refs/heads/master' && github.run_id || github.ref }}
  cancel-in-progress: true

env:
  MOCHA_OPTIONS: ${{ github.ref == 'refs/heads/master' && '--retries 1' || '' }}
  LATEST_VERSION: ${{ inputs.latest-version }}

jobs:
  macos:
    name: ${{ github.workflow }} / macos
    runs-on: macos-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/dd-sts-api-key
        id: dd-sts
      - uses: ./.github/actions/node/latest
      - uses: ./.github/actions/install
      - run: yarn test:profiler:ci
      - run: yarn test:integration:profiler:coverage
      - uses: ./.github/actions/coverage
        with:
          flags: profiling-macos
          dd_api_key: ${{ steps.dd-sts.outputs.api_key }}
      - uses: ./.github/actions/push_to_test_optimization
        if: "!cancelled()"
        with:
          dd_api_key: ${{ steps.dd-sts.outputs.api_key }}

  ubuntu:
    name: ${{ github.workflow }} / ubuntu
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/dd-sts-api-key
        id: dd-sts
      - uses: ./.github/actions/node/oldest-maintenance-lts
      - uses: ./.github/actions/install
      - run: yarn test:profiler:ci
      - run: yarn test:integration:profiler:coverage
      - uses: ./.github/actions/node/newest-maintenance-lts
      - run: yarn test:profiler:ci
      - run: yarn test:integration:profiler:coverage
      - uses: ./.github/actions/node/active-lts
      - run: yarn test:profiler:ci
      - run: yarn test:integration:profiler:coverage
      - uses: ./.github/actions/node/latest
      - run: yarn test:profiler:ci
      - run: yarn test:integration:profiler:coverage
      - uses: ./.github/actions/coverage
        with:
          flags: profiling-ubuntu
          dd_api_key: ${{ steps.dd-sts.outputs.api_key }}
      - uses: ./.github/actions/push_to_test_optimization
        if: "!cancelled()"
        with:
          dd_api_key: ${{ steps.dd-sts.outputs.api_key }}

  windows:
    name: ${{ github.workflow }} / windows
    runs-on: windows-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/dd-sts-api-key
        id: dd-sts
      - uses: ./.github/actions/node/latest
      - uses: ./.github/actions/install
        with:
          cache: "true"
      - run: yarn test:profiler:ci
      - run: yarn test:integration:profiler:coverage
      - uses: ./.github/actions/upload-node-reports
        if: failure()
        with:
          name: profiling-windows
      - uses: ./.github/actions/coverage
        with:
          flags: profiling-windows
          dd_api_key: ${{ steps.dd-sts.outputs.api_key }}
      - uses: ./.github/actions/push_to_test_optimization
        if: "!cancelled()"
        with:
          dd_api_key: ${{ steps.dd-sts.outputs.api_key }}
