name: 'Release Proposal Test'

on:
  push:
    branches:
      - release-proposal-test-2

jobs:
  create-proposal:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - uses: ./.github/actions/node
      - run: npm i -g branch-diff
      - run: |
          mkdir -p ~/.config/changelog-maker
          echo "{\"token\":\"${{secrets.GITHUB_TOKEN}}\",\"user\":\"${{github.actor}}\"}" > ~/.config/changelog-maker/config.json
      - run: node scripts/release/proposal 5 --auto --debug
