name: "Release Validation"

on:
  push:
    branches:
      - v[0-9]+.[0-9]+.[0-9]+-proposal

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate-proposal:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      id-token: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
      - name: Get GitHub Token via dd-octo-sts
        id: generate-token
        uses: DataDog/dd-octo-sts-action@96a25462dbcb10ebf0bfd6e2ccc917d2ab235b9a # v1.0.4
        with:
          scope: DataDog/dd-trace-js
          policy: self.release-validate
      - uses: ./.github/actions/node
        with:
          version: ""
      - uses: ./.github/actions/install/branch-diff
        with:
          token: ${{ steps.generate-token.outputs.token }}
      - run: node scripts/release/validate
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
