name: Serverless Integration Test

on:
  pull_request:
  push:
    branches: [master]
  schedule:
    - cron: 0 4 * * *
    - cron: 20 4 * * *
    - cron: 40 4 * * *

jobs:
  integration:
    # Google Auth permissions
    permissions:
      contents: 'read'
      id-token: 'write'
    strategy:
      matrix:
        version: [18, latest]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version: ${{ matrix.version }}
      - uses: ./.github/actions/install
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@71f986410dfbc7added4569d411d040a91dc6935 # v2.1.8
        with:
          service_account: ${{ secrets.SERVERLESS_GCP_SERVICE_ACCOUNT }}
          workload_identity_provider: ${{ secrets.SERVERLESS_GCP_WORKLOAD_IDENTITY_PROVIDER }}
      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@77e7a554d41e2ee56fc945c52dfd3f33d12def9a # v2.1.4
      - name: Run serverless integration test
        run: yarn test:integration:serverless
