name: Serverless Integration Test

on:
  pull_request:
  push:
    branches: [master]
  schedule:
    - cron: 0 4 * * *
    - cron: 20 4 * * *
    - cron: 40 4 * * *

jobs:
  integration:
    # Google Auth permissions
    permissions:
      contents: 'read'
      id-token: 'write'
    strategy:
      matrix:
        version: [18, latest]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ./.github/actions/node/setup
      - uses: ./.github/actions/install
      - uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version: ${{ matrix.version }}
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@6fc4af4b145ae7821d527454aa9bd537d1f2dc5f # v2.1.7
        with:
          service_account: ${{ secrets.SERVERLESS_GCP_SERVICE_ACCOUNT }}
          workload_identity_provider: ${{ secrets.SERVERLESS_GCP_WORKLOAD_IDENTITY_PROVIDER }}
      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@6189d56e4096ee891640bb02ac264be376592d6a # v2.1.2
      - name: Run serverless integration test
        run: yarn test:integration:serverless
