name: Serverless Integration Test

on:
  pull_request:
  push:
    branches: [master]
  schedule:
    - cron: "0 4 * * *"

jobs:
  integration:
    # Google Auth permissions
    permissions:
      contents: 'read'
      id-token: 'write'
    strategy:
      matrix:
        version: [18, latest]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/node/setup
      - uses: ./.github/actions/install
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.version }}
      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          service_account: ${{ secrets.SERVERLESS_GCP_SERVICE_ACCOUNT }}
          workload_identity_provider: ${{ secrets.SERVERLESS_GCP_WORKLOAD_IDENTITY_PROVIDER }}
      - name: Setup Google Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'
      - name: Run serverless integration test
        run: yarn test:integration:serverless
