name: Serverless Integration Test

on:
  pull_request:
  push:
    branches: [master]
  schedule:
    - cron: 0 4 * * *
    - cron: 20 4 * * *
    - cron: 40 4 * * *

jobs:
  integration:
    # Google Auth permissions
    permissions:
      contents: 'read'
      id-token: 'write'
    strategy:
      matrix:
        version: [oldest, latest]
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/checkout
      - uses: ./.github/actions/node
        with:
          version: ${{ matrix.version }}
      - uses: ./.github/actions/install
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@6fc4af4b145ae7821d527454aa9bd537d1f2dc5f # v2.1.7
        with:
          service_account: ${{ secrets.SERVERLESS_GCP_SERVICE_ACCOUNT }}
          workload_identity_provider: ${{ secrets.SERVERLESS_GCP_WORKLOAD_IDENTITY_PROVIDER }}
      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@6189d56e4096ee891640bb02ac264be376592d6a # v2.1.2
      - name: Run serverless integration test
        run: yarn test:integration:serverless
