name: Serverless Integration Test

on:
  pull_request:
  push:
    branches: [master]

jobs:
  integration:
    # Google Auth permissions
    permissions:
      contents: 'read'
      id-token: 'write'
    strategy:
      matrix:
        version: [16, latest]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/node/setup
      - run: yarn install
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v1'
        with:
          service_account: ${{ secrets.SERVERLESS_GCP_SERVICE_ACCOUNT }}
          workload_identity_provider: ${{ secrets.SERVERLESS_GCP_WORKLOAD_IDENTITY_PROVIDER }}
      - name: Setup Google Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v1'
      - name: Run serverless integration test
        run: yarn test:integration:serverless
