name: Serverless performance test

on:
  pull_request:
  push:
    branches: [master]

jobs:
  performance-test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        node-version: [14.15, 16.14, 18.12]
    steps:
      - name: Checkout dd-trace-js
        uses: actions/checkout@v3
      - name: Checkout datadog-lambda-js
        uses: actions/checkout@v3
        with:
          repository: DataDog/datadog-lambda-js
          # TODO remove hardcoded branch when merged to main
          ref: refs/heads/maxday/add-git
          path: datadog-lambda-js
      - name: Update package.json to the current ref
        run: |
          cd datadog-lambda-js
          yarn add https://github.com/DataDog/dd-trace-js#refs/heads/$GITHUB_HEAD_REF --save-dev
      - name: Build the layer
        env:
          NODE_VERSION: ${{ matrix.node-version }}
        run: |
          cd datadog-lambda-js 
          ./scripts/build_layers.sh
      - name: Rename layer to 'layer.zip'
        run: mv datadog-lambda-js/.layers/datadog_lambda_node${{ matrix.node-version }}.zip ./layer.zip
      - name: Deploy
        uses: DataDog/serverless-performance-test-action@main
        with:
          runtime_id: 'maxday-runtime'
          layer_path: './layer.zip'
          layer_name: 'performance-tester-nodejs-${{ matrix.node-version }}'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.SERVERLESS_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SERVERLESS_AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: sa-east-1