name: Serverless performance test

on:
  pull_request:
  push:
    branches: [master]

jobs:
  performance-test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        node-version: [12.13, 14.15, 16.14, 18.12]
    steps:
      - name: Checkout dd-trace-js
        uses: actions/checkout@v3
      - name: Checkout datadog-lambda-js
        uses: actions/checkout@v3
        with:
          repository: DataDog/datadog-lambda-js
          # TODO remove hardcoded branch when merged to main
          ref: refs/heads/maxday/add-git
          path: datadog-lambda-js
      - name: Update package.json to the current ref
        # TODO node_version hardcoded for now, switch to matrix for all supported version of node
        run: |
          cd datadog-lambda-js
          yarn add https://github.com/DataDog/dd-trace-js#refs/heads/$GITHUB_HEAD_REF --save-dev
      - name: Build the layer
        run: NODE_VERSION=${{ matrix.node-version }} ./scripts/build_layers.sh
      - uses: ./.github/actions/serverless