name: Start the Datadog APM TestAgent 2

on:
  workflow_call:

jobs:
  start_testagent_other:
    name: Start the Datadog APM Test Agent
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker-compose up -d testagent