name: Start the Datadog APM TestAgent 2

on:
  workflow_call:

jobs:
  start_testagent_other:
    name: Start the Datadog APM Test Agent
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker run -d \
          --name testagent \
          -p 127.0.0.1:9126:9126 \
          -e LOG_LEVEL=DEBUG \
          -e TRACE_LANGUAGE=javascript \
          -e DISABLED_CHECKS=trace_content_length \
          -e PORT=9126 \
          ghcr.io/datadog/dd-apm-test-agent/ddapm-test-agent:latest