name: Start the Datadog APM TestAgent

on:
  workflow_call:
    # Map the workflow outputs to job outputs
    outputs:
      container_id:
        description: "Container ID of TestAgent"
        value: ${{ jobs.start_testagent.outputs.container_id }}

jobs:
  start_testagent:
    name: Start the Datadog APM Test Agent
    runs-on: ubuntu-latest
    outputs:
      container_id: ${{ steps.get_container_id.outputs.container_id }}
    steps:
      # - run: docker-compose up -d testagent
      - run: docker run -d \
          --name testagent \
          -p 127.0.0.1:9126:9126 \
          -e LOG_LEVEL=DEBUG \
          -e TRACE_LANGUAGE=javascript \
          -e DISABLED_CHECKS=trace_content_length \
          -e PORT=9126 \
          ghcr.io/datadog/dd-apm-test-agent/ddapm-test-agent:latest
      - name: Get TestAgent Container ID
        id: get_container_id
        run: echo "container_id=$(docker ps -aqf \"name=testagent\")" >> $GITHUB_ENV