# How to configure:
#
# When no team is frozen, set `frozen-teams` to an empty string:
# frozen-teams: ""
#
# When one or more teams are frozen, add them one per line with the @DataDog prefix:
#
# frozen-teams: |
#   @DataDog/team-a
#   @DataDog/team-b

name: Team freeze guard

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
      - labeled
      - unlabeled
      - ready_for_review

permissions:
  id-token: write
  contents: read

jobs:
  team-freeze-guard:
    name: Team freeze guard
    runs-on: ubuntu-latest

    steps:
      - uses: DataDog/team-freeze-guard@e4ff51a72cac229b238e5a302af0d3d955ae5b54 # v0.0.4
        with:
          bypass-labels: |
            dev/testing
            github_actions
          frozen-teams: |
            @DataDog/apm-idm-js
            @DataDog/ml-observability
            @DataDog/lang-platform-js
